#!/usr/bin/env python3
"""Generate the ov-watchdog mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

🔴 GENERATED, NOT HAND-WRITTEN, so a mutant can only ever differ from src by
its one intended change.

Run from tools/watchdog-test/: python3 mut/make.py
"""
src = open('../../src/ov-watchdog.js').read()
# A mutant lives in mut/, two levels below src/, so the element's own relative
# imports are rewritten or every mutant dies at import time, which the gate
# would report as a throw rather than as the refusal failing.
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. A fresh beat with a held counter proves the stage alive.
mut('a-running-is-working',
    "      else if (now - b.movedAt > limit) { row.state = 'stalled'; row.held = (now - b.movedAt) / 1000; }",
    "      else if (false) { row.state = 'stalled'; }  // MUTANT: running counts as working")

# b: a monitor vouches for the feed it guards.
mut('b-vouches-for-own-feed',
    "      if (row.feed && guardedFeeds.has(row.feed)) row.state = 'shared';",
    "      if (false) row.state = 'shared';  // MUTANT: its own feed may vouch for it")

# c: a panel showing an alert is called quiet.
mut('c-alerting-is-quiet',
    "        if (s.tiles.every((t) => t.state === 'normal')) return true;",
    "        return true;  // MUTANT: quiet whatever the panel shows")

# d: a watchdog that proves its path clears every other watchdog's claim.
mut('d-clears-other-claims',
    "    g._ovUnproven?.delete(this._vid);",
    "    g._ovUnproven?.clear();  // MUTANT: one proof clears all claims")

# e: losing the path is not announced.
mut('e-unannounced',
    "        this.say(proven ? `${this.labelText()}: path proven live` : `${this.labelText()}: path not proven, ${whySay}`);",
    "        void 0;  // MUTANT: say nothing")
