/* GENERATED by tools/gen_shaders.py from every .glsl here. Do not edit; edit the .glsl and re-run. */
/* Shader name -> loader. Literal imports so bundlers can see every file;
 * functions so nothing loads until an element names it. */
export const SHADERS = {
  'beam': () => import('./beam.js'),
  'fault': () => import('./fault.js'),
  'field': () => import('./field.js'),
  'filmloop': () => import('./filmloop.js'),
  'holo': () => import('./holo.js'),
  'ornament': () => import('./ornament.js'),
  'rain': () => import('./rain.js'),
  'scope': () => import('./scope.js'),
  'vision': () => import('./vision.js'),
  'waterfall': () => import('./waterfall.js'),
};
