#!/usr/bin/env python3
"""Generate the ov-mosaic mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

A green gate run only proves the harness runs; these prove it can fail.
Run from tools/mosaic-test/: python3 mut/make.py
"""
src = open('../../src/ov-mosaic.js').read()
# 🔴 A MUTANT LIVES IN mut/, TWO LEVELS BELOW src/, so the element's own
# relative imports have to be rewritten or every mutant dies at import time -
# which the gate reports as a THROW, not as the refusal failing. A mutant that
# cannot load proves nothing about the refusal it was made to break.
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. The header quotes the compile time, as Garmin's display does.
mut('a-compile-age',
    "      r.ageS = (now - r.oldest) / 1000;",
    "      r.ageS = r.compiledS;  // MUTANT: the age of the stitch, not of the data")

# b: three absences drawn and named as one, the fault AC 00-45H and Garmin show.
mut('b-one-grey',
    "const STATUS_COVER = { down: 'site-down', awaited: 'awaited', 'not-selected': 'not-selected' };",
    "const STATUS_COVER = { down: 'site-down', awaited: 'awaited', 'not-selected': 'not-selected' };\n"
    "// MUTANT: every absence becomes one word in one class.\n"
    "for (const k of Object.keys(COVER)) COVER[k] = { word: 'NO COVERAGE', fills: true };")

# c: the expired product dimmed and left up instead of removed.
mut('c-dim-expired',
    "    const drawable = pic && r.state !== 'expired' && r.state !== 'overflow';",
    "    const drawable = pic && r.state !== 'overflow';  // MUTANT: expired stays on screen")

# d: an undated part skipped, so the oldest DATED part is offered as the answer.
mut('d-newest-known',
    "      if (!s.dated) r.undated.push(s.id);\n"
    "      else if (r.oldest === null || s.at < r.oldest) { r.oldest = s.at; r.oldestId = s.id; }",
    "      if (!s.dated) continue;  // MUTANT: no scan time, no mention\n"
    "      if (r.oldest === null || s.at < r.oldest) { r.oldest = s.at; r.oldestId = s.id; }")

# e: a site that has stopped keeps its last picture painted on the map.
mut('e-stale-territory',
    "          if (s.status === 'up') { cell.src = s.id; s.cells++; } "
    "else { cell.cover = STATUS_COVER[s.status]; cell.src = s.id; }",
    "          cell.src = s.id; s.cells++;  // MUTANT: a down site keeps its last cells")
