#!/usr/bin/env python3
"""Generate the ov-position mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

A green gate run only proves the harness runs; these prove it can fail.
Run from tools/position-test/: python3 mut/make.py
"""
src = open('../../src/ov-position.js').read()
# 🔴 A MUTANT LIVES IN mut/, TWO LEVELS BELOW src/, so the element's own
# relative imports have to be rewritten or every mutant dies at import time -
# which the gate reports as a THROW, not as the refusal failing. A mutant that
# cannot load proves nothing about the refusal it was made to break.
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline, and the Royal Majesty's actual fault. A position whose mode
# the element does not recognise is taken for a fix - which is what a receiver
# calling itself a "GP" talker in DR mode amounts to.
mut('a-mode-from-label',
    "    const mode = Object.hasOwn(MODE, f.mode) ? f.mode : null;",
    "    const mode = Object.hasOwn(MODE, f.mode) ? f.mode : 'fix';  "
    "// MUTANT: no mode flag, call it a fix")

# b: one ring for both claims - accuracy drawn where containment belongs.
mut('b-one-ring',
    "      set('.ov-position__cont', f.containment);",
    "      set('.ov-position__cont', f.accuracy);  // MUTANT: accuracy stands for both")

# c: a containment with no stated probability treated as a bound.
mut('c-bound-unbounded',
    "    r.unbounded = finite(f.containment) && prob(f.containmentP) === null;",
    "    r.unbounded = false;  // MUTANT: every radius is a bound")

# d: a claimed MEDIUM integrity kept even when the cross-check shares inputs.
mut('d-medium-unearned',
    "    if (f.second && f.second.shares && f.integrity && INTEGRITY[f.integrity].rank >= 2) {",
    "    if (false && f.second && f.second.shares) {  // MUTANT: take the claim as given")

# e: every position printed to four decimals, whatever its accuracy.
mut('e-full-digits',
    "    return clamp(Math.ceil(Math.log10(M_PER_DEG / accuracy)), 0, MAX_PLACES);",
    "    return MAX_PLACES;  // MUTANT: all the digits, all the time")

# f: a position that misses the requirement withheld instead of qualified.
mut('f-withhold-on-miss',
    "    setText(q('.ov-position__latlon'), noPos ? '—' : this.latlon(r, f));",
    "    setText(q('.ov-position__latlon'), noPos || r.missesReq ? '—' : this.latlon(r, f));  "
    "// MUTANT: withhold rather than qualify")
