#!/usr/bin/env python3
"""Generate the ov-avatar mutants: one copy per refusal, each broken on purpose.
The gate MUST go red against every one.

Run from tools/avatar-test/: python3 mut/make.py
"""
src = open('../../src/ov-avatar.js').read()
src = src.replace("from './ov-core.js'", "from '../../../src/ov-core.js'")
head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. A slot with no kind gets the stock human.
mut('a-default-human',
    "const kind = Object.hasOwn(KINDS, rawKind) ? rawKind : null;",
    "const kind = Object.hasOwn(KINDS, rawKind) ? rawKind : 'human';  // MUTANT")

# b: an empty seat still carries the status it was handed.
mut('b-status-on-empty',
    "else if (r.state === 'unassigned' || r.state === 'conflict') r.ignored.push('status');",
    "else if (false) r.ignored.push('status');  // MUTANT")

# c: a silhouette with no name reads as a normal assignment.
mut('c-unnamed-passes',
    "    } else if (!name) {\n      r.state = 'unnamed';",
    "    } else if (false) {  // MUTANT\n      r.state = 'unnamed';")

# d: the empty well is drawn solid, so it reads as a filled seat.
mut('d-slot-solid',
    "      pic = '<rect class=\"ov-avatar__slot\" x=\"3\" y=\"3\" width=\"94\" height=\"94\" rx=\"12\"/>';",
    "      pic = '<rect class=\"ov-avatar__well\" x=\"2\" y=\"2\" width=\"96\" height=\"96\" rx=\"12\"/>'; /* MUTANT */")

# e: an inner detail comes back: a visor cut out of the crew helmet.
mut('e-inner-detail',
    "      suit: disc(50, 34, 24) + ",
    "      suit: disc(50, 34, 24) + '<rect class=\"ov-avatar__well\" x=\"34\" y=\"26\" width=\"32\" height=\"12\"/>' + /* MUTANT */ ")

# f: the old android comes back, a thin neck between two pistons: holes in the shape.
mut('f-holes-in-neck',
    "        + box(26, 27, 9, 15, 2) + box(65, 27, 9, 15, 2),",
    "        + box(26, 27, 9, 15, 2) + box(65, 27, 9, 15, 2) + box(38, 54, 3, 11) + box(59, 54, 3, 11) + '<rect class=\"ov-avatar__body\" x=\"30\" y=\"54\" width=\"40\" height=\"2\"/>', /* MUTANT */")

# g: the figure fills the whole well again, with no room around it.
mut('g-no-room', "const FIGURE_SCALE = 0.8;", "const FIGURE_SCALE = 1; /* MUTANT */")
