<!-- GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. -->
<script>
  /* ov-annunciator
   *
   * Svelte 5 replaced the `on:` directive with plain properties, so a
   * colon-namespaced event has NO declarative spelling: `onov:acknowledge` is not
   * an identifier. Events arrive as callback props and are attached here.
   */
  import '../ov-annunciator.js';

  let { conditions = undefined, onacknowledge = undefined, onannunciate = undefined, onshelve = undefined, children, ...rest } = $props();

  let host = $state(null);

  /* 🔴 `rest` is applied with setAttribute rather than spread onto the element.
   * Svelte's custom-element path sets a prop as a PROPERTY when the name
   * exists on the element, and this kit has 47 getter-only properties whose
   * names collide with real attributes (digits, step, lat, range, duration).
   * Assigning one throws. See the React runtime for the full account. */
  $effect(() => {
    if (!host) return;
    for (const [key, value] of Object.entries(rest)) {
      const name = key === 'className' ? 'class' : key;
      if (value === null || value === undefined || value === false) host.removeAttribute(name);
      else if (value === true) host.setAttribute(name, '');
      else host.setAttribute(name, String(value));
    }
  });

  $effect(() => {
    if (host && conditions !== undefined) host.conditions = conditions;
  });

  $effect(() => {
    if (!host) return;
    const off = [
      (() => { const h = (e) => onacknowledge?.(e); host.addEventListener('ov:acknowledge', h); return () => host.removeEventListener('ov:acknowledge', h); })(),
      (() => { const h = (e) => onannunciate?.(e); host.addEventListener('ov:annunciate', h); return () => host.removeEventListener('ov:annunciate', h); })(),
      (() => { const h = (e) => onshelve?.(e); host.addEventListener('ov:shelve', h); return () => host.removeEventListener('ov:shelve', h); })(),
    ];
    return () => off.forEach((f) => f());
  });
</script>

<svelte:element this={'ov-annunciator'} bind:this={host}>{@render children?.()}</svelte:element>
