<!-- GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. -->
<script>
  /* ov-procedure
   *
   * Svelte 5 replaced the `on:` directive with plain properties, so a
   * colon-namespaced event has NO declarative spelling: `onov:claim` is not
   * an identifier. Events arrive as callback props and are attached here.
   */
  import '../ov-procedure.js';

  let { sensed = undefined, onclaim = undefined, oncomplete = undefined, onrefuse = undefined, children, ...rest } = $props();

  let host = $state(null);

  /* 🔴 `rest` is applied with setAttribute rather than spread onto the element.
   * Svelte's custom-element path sets a prop as a PROPERTY when the name
   * exists on the element, and this kit has 47 getter-only properties whose
   * names collide with real attributes (digits, step, lat, range, duration).
   * Assigning one throws. See the React runtime for the full account. */
  $effect(() => {
    if (!host) return;
    for (const [key, value] of Object.entries(rest)) {
      const name = key === 'className' ? 'class' : key;
      if (value === null || value === undefined || value === false) host.removeAttribute(name);
      else if (value === true) host.setAttribute(name, '');
      else host.setAttribute(name, String(value));
    }
  });

  $effect(() => {
    if (host && sensed !== undefined) host.sensed = sensed;
  });

  $effect(() => {
    if (!host) return;
    const off = [
      (() => { const h = (e) => onclaim?.(e); host.addEventListener('ov:claim', h); return () => host.removeEventListener('ov:claim', h); })(),
      (() => { const h = (e) => oncomplete?.(e); host.addEventListener('ov:complete', h); return () => host.removeEventListener('ov:complete', h); })(),
      (() => { const h = (e) => onrefuse?.(e); host.addEventListener('ov:refuse', h); return () => host.removeEventListener('ov:refuse', h); })(),
    ];
    return () => off.forEach((f) => f());
  });
</script>

<svelte:element this={'ov-procedure'} bind:this={host}>{@render children?.()}</svelte:element>
