<!-- GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. -->
<script>
  /* ov-switch
   *
   * Svelte 5 replaced the `on:` directive with plain properties, so a
   * colon-namespaced event has NO declarative spelling: `onov:arm` is not
   * an identifier. Events arrive as callback props and are attached here.
   */
  import '../ov-switch.js';

  let { reading = undefined, talkback = undefined, onarm = undefined, oncommand = undefined, onsafe = undefined, children, ...rest } = $props();

  let host = $state(null);

  /* 🔴 `rest` is applied with setAttribute rather than spread onto the element.
   * Svelte's custom-element path sets a prop as a PROPERTY when the name
   * exists on the element, and this kit has 47 getter-only properties whose
   * names collide with real attributes (digits, step, lat, range, duration).
   * Assigning one throws. See the React runtime for the full account. */
  $effect(() => {
    if (!host) return;
    for (const [key, value] of Object.entries(rest)) {
      const name = key === 'className' ? 'class' : key;
      if (value === null || value === undefined || value === false) host.removeAttribute(name);
      else if (value === true) host.setAttribute(name, '');
      else host.setAttribute(name, String(value));
    }
  });

  $effect(() => {
    if (host && reading !== undefined) host.reading = reading;
    if (host && talkback !== undefined) host.talkback = talkback;
  });

  $effect(() => {
    if (!host) return;
    const off = [
      (() => { const h = (e) => onarm?.(e); host.addEventListener('ov:arm', h); return () => host.removeEventListener('ov:arm', h); })(),
      (() => { const h = (e) => oncommand?.(e); host.addEventListener('ov:command', h); return () => host.removeEventListener('ov:command', h); })(),
      (() => { const h = (e) => onsafe?.(e); host.addEventListener('ov:safe', h); return () => host.removeEventListener('ov:safe', h); })(),
    ];
    return () => off.forEach((f) => f());
  });
</script>

<svelte:element this={'ov-switch'} bind:this={host}>{@render children?.()}</svelte:element>
