/* GENERATED by tools/api.py. Do not edit; re-run the script.
 *
 * Types for consumers, derived from the same manifest the reference pages and
 * the framework wrappers come from, so all three say the same thing.
 *
 * ⚠️ NOT INFERRED FROM THE SOURCE. Pointing tsc at src/*.js produced 291
 * errors that were almost entirely undeclared instance fields and
 * `window.Overscan`, none of which is part of the public API. Inferring a
 * public contract from private implementation detail would have shipped a
 * worse answer than the manifest already holds.
 */

/** A single reading handed to a readout.
 *
 * `null` is a DROPOUT and renders a refusal. It is never coerced to 0 and
 * never dropped from an array. A string is passed through unnormalised, so
 * "01.50" stays "01.50" rather than becoming 1.5.
 */
export type Reading = number | string | null | { value: number; age?: number | null };

/** Structured data. Carries no refusal protocol: see the per-element notes.
 *  An array (rows, spans, conditions) or an object (a plan, a survey, the air
 *  data): `unknown[]` alone typed ov-wireframe's survey and ov-schematic's plan
 *  as arrays, which they are not. */
export type Structured = unknown[] | Record<string, unknown>;

export declare const Overscan: Record<string, any>;
export declare function define<T extends CustomElementConstructor>(
  name: string, cls: T): T;


/** `<ov-allocator>`
 *  Events: ov:allocate, ov:refuse.
 */
export interface OvAllocator extends HTMLElement {
  readback: Structured;
}

/** `<ov-annunciator>`
 *  Events: ov:acknowledge, ov:annunciate, ov:shelve.
 */
export interface OvAnnunciator extends HTMLElement {
  conditions: Structured;
}

/** `<ov-ansi>`
 */
export interface OvAnsi extends HTMLElement {
}

/** `<ov-spark>`
 *  Reading property: values.
 *  Marks staleness: NO.
 */
export interface OvSpark extends HTMLElement {
  values: Reading[] | null;
}

/** `<ov-cellbar>`
 *  Reading property: value.
 *  Marks staleness: NO.
 */
export interface OvCellbar extends HTMLElement {
  value: Reading;
}

/** `<ov-avatar>`
 */
export interface OvAvatar extends HTMLElement {
}

/** `<ov-balance>`
 */
export interface OvBalance extends HTMLElement {
  reading: Structured;
}

/** `<ov-baseline>`
 *  Events: ov:baseline, ov:refuse.
 */
export interface OvBaseline extends HTMLElement {
  samples: Structured;
}

/** `<ov-chart>`
 *  Reading property: values.
 *  Marks staleness: NO.
 */
export interface OvChart extends HTMLElement {
  values: Reading[] | null;
}

/** `<ov-clearance>`
 */
export interface OvClearance extends HTMLElement {
  pick: Structured;
}

/** `<ov-cli>`
 *  Events: ov:command.
 */
export interface OvCli extends HTMLElement {
}

/** `<ov-consistency>`
 */
export interface OvConsistency extends HTMLElement {
  watch: Structured;
}

/** `<ov-continuity>`
 */
export interface OvContinuity extends HTMLElement {
  streams: Structured;
}

/** `<ov-countdown>`
 *  Reading property: clock.
 *  Marks staleness: NO.
 *  Events: ov:clock.
 */
export interface OvCountdown extends HTMLElement {
  clock: Reading;
}

/** `<ov-coverage>`
 */
export interface OvCoverage extends HTMLElement {
  coverage: Structured;
}

/** `<ov-dial>`
 *  Events: ov:change.
 */
export interface OvDial extends HTMLElement {
}

/** `<ov-donut>`
 */
export interface OvDonut extends HTMLElement {
  parts: Structured;
}

/** `<ov-dose>`
 */
export interface OvDose extends HTMLElement {
  order: Structured;
}

/** `<ov-downlink>`
 *  Events: ov:signal.
 */
export interface OvDownlink extends HTMLElement {
}

/** `<ov-ecg>`
 *  Events: ov:ecg.
 */
export interface OvEcg extends HTMLElement {
  samples: Structured;
}

/** `<ov-endurance>`
 */
export interface OvEndurance extends HTMLElement {
  supply: Structured;
}

/** `<ov-fan>`
 */
export interface OvFan extends HTMLElement {
  forecast: Structured;
}

/** `<ov-fault>`
 */
export interface OvFault extends HTMLElement {
}

/** `<ov-field>`
 */
export interface OvField extends HTMLElement {
}

/** `<ov-flap>`
 *  Reading property: value.
 *  Marks staleness: yes.
 */
export interface OvFlap extends HTMLElement {
  value: Reading;
}

/** `<ov-gauge>`
 *  Reading property: value.
 *  Marks staleness: yes.
 */
export interface OvGauge extends HTMLElement {
  value: Reading;
}

/** `<ov-geomap>`
 */
export interface OvGeomap extends HTMLElement {
  countriesData: Structured;
  routes: Structured;
}

/** `<ov-graph>`
 */
export interface OvGraph extends HTMLElement {
}

/** `<ov-node>`
 */
export interface OvNode extends HTMLElement {
}

/** `<ov-socket>`
 */
export interface OvSocket extends HTMLElement {
}

/** `<ov-link>`
 */
export interface OvLink extends HTMLElement {
}

/** `<ov-grid>`
 */
export interface OvGrid extends HTMLElement {
}

/** `<ov-histogram>`
 */
export interface OvHistogram extends HTMLElement {
  histogram: Structured;
}

/** `<ov-hold>`
 *  Events: ov:cancel, ov:commit.
 */
export interface OvHold extends HTMLElement {
}

/** `<ov-horizon>`
 */
export interface OvHorizon extends HTMLElement {
  air: Structured;
}

/** `<ov-icon>`
 */
export interface OvIcon extends HTMLElement {
}

/** `<ov-ladder>`
 */
export interface OvLadder extends HTMLElement {
  chain: Structured;
}

/** `<ov-likelihood>`
 */
export interface OvLikelihood extends HTMLElement {
  finding: Structured;
}

/** `<ov-locator>`
 */
export interface OvLocator extends HTMLElement {
  fixes: Structured;
}

/** `<ov-log>`
 */
export interface OvLog extends HTMLElement {
}

/** `<ov-map>`
 */
export interface OvMap extends HTMLElement {
}

/** `<ov-match>`
 */
export interface OvMatch extends HTMLElement {
  result: Structured;
}

/** `<ov-menu>`
 */
export interface OvMenu extends HTMLElement {
}

/** `<ov-modal>`
 */
export interface OvModal extends HTMLElement {
}

/** `<ov-mosaic>`
 */
export interface OvMosaic extends HTMLElement {
  picture: Structured;
}

/** `<ov-orbit>`
 */
export interface OvOrbit extends HTMLElement {
  prediction: Structured;
}

/** `<ov-ornament>`
 */
export interface OvOrnament extends HTMLElement {
}

/** `<ov-plate>`
 *  Events: ov:view.
 */
export interface OvPlate extends HTMLElement {
  detections: Structured;
}

/** `<ov-player>`
 *  Events: ov:player.
 */
export interface OvPlayer extends HTMLElement {
  media: Structured;
}

/** `<ov-polygon>`
 */
export interface OvPolygon extends HTMLElement {
  axes: Structured;
}

/** `<ov-position>`
 */
export interface OvPosition extends HTMLElement {
  fix: Structured;
}

/** `<ov-procedure>`
 *  Events: ov:claim, ov:complete, ov:refuse.
 */
export interface OvProcedure extends HTMLElement {
  sensed: Structured;
}

/** `<ov-quorum>`
 *  Events: ov:quorum.
 */
export interface OvQuorum extends HTMLElement {
  readings: Structured;
}

/** `<ov-radar>`
 */
export interface OvRadar extends HTMLElement {
}

/** `<ov-rangebar>`
 */
export interface OvRangebar extends HTMLElement {
  channels: Structured;
}

/** `<ov-reticle>`
 */
export interface OvReticle extends HTMLElement {
}

/** `<ov-schematic>`
 */
export interface OvSchematic extends HTMLElement {
  plan: Structured;
  states: Structured;
}

/** `<ov-scope>`
 */
export interface OvScope extends HTMLElement {
}

/** `<ov-score>`
 */
export interface OvScore extends HTMLElement {
  reading: Structured;
}

/** `<ov-segment>`
 *  Reading property: value.
 *  Marks staleness: yes.
 */
export interface OvSegment extends HTMLElement {
  value: Reading;
}

/** `<ov-sequence>`
 */
export interface OvSequence extends HTMLElement {
  sequence: Structured;
}

/** `<ov-sound-switch>`
 */
export interface OvSoundSwitch extends HTMLElement {
}

/** `<ov-split>`
 */
export interface OvSplit extends HTMLElement {
}

/** `<ov-station>`
 *  Events: ov:station.
 */
export interface OvStation extends HTMLElement {
  observation: Structured;
}

/** `<ov-switch>`
 *  Events: ov:arm, ov:command, ov:safe.
 */
export interface OvSwitch extends HTMLElement {
  reading: Structured;
  talkback: Structured;
}

/** `<ov-table>`
 *  Events: ov:reorder.
 */
export interface OvTable extends HTMLElement {
  cols: Structured;
  rows: Structured;
}

/** `<ov-tactical>`
 *  Events: ov:view.
 */
export interface OvTactical extends HTMLElement {
  countriesData: Structured;
  data: Structured;
}

/** `<ov-term>`
 */
export interface OvTerm extends HTMLElement {
}

/** `<ov-text>`
 */
export interface OvText extends HTMLElement {
  source: Structured;
}

/** `<ov-timeline>`
 *  Events: ov:seek, ov:solo.
 */
export interface OvTimeline extends HTMLElement {
  spans: Structured;
}

/** `<ov-timestack>`
 */
export interface OvTimestack extends HTMLElement {
  stamp: Structured;
}

/** `<ov-topology>`
 */
export interface OvTopology extends HTMLElement {
  topology: Structured;
}

/** `<ov-track>`
 */
export interface OvTrack extends HTMLElement {
}

/** `<ov-transport>`
 *  Events: ov:pause, ov:play, ov:seek.
 */
export interface OvTransport extends HTMLElement {
}

/** `<ov-tree>`
 *  Events: ov:reorder.
 */
export interface OvTree extends HTMLElement {
}

/** `<ov-verifier>`
 *  Events: ov:verify.
 */
export interface OvVerifier extends HTMLElement {
  commands: Structured;
}

/** `<ov-vitals>`
 *  Events: ov:vitals.
 */
export interface OvVitals extends HTMLElement {
  vitals: Structured;
}

/** `<ov-waterfall>`
 */
export interface OvWaterfall extends HTMLElement {
}

/** `<ov-wave>`
 */
export interface OvWave extends HTMLElement {
}

/** `<ov-window>`
 *  Events: ov:resize.
 */
export interface OvWindow extends HTMLElement {
}

/** `<ov-wireframe>`
 */
export interface OvWireframe extends HTMLElement {
  figures: Structured;
  survey: Structured;
}

declare global {
  interface HTMLElementTagNameMap {
    'ov-allocator': OvAllocator;
    'ov-annunciator': OvAnnunciator;
    'ov-ansi': OvAnsi;
    'ov-spark': OvSpark;
    'ov-cellbar': OvCellbar;
    'ov-avatar': OvAvatar;
    'ov-balance': OvBalance;
    'ov-baseline': OvBaseline;
    'ov-chart': OvChart;
    'ov-clearance': OvClearance;
    'ov-cli': OvCli;
    'ov-consistency': OvConsistency;
    'ov-continuity': OvContinuity;
    'ov-countdown': OvCountdown;
    'ov-coverage': OvCoverage;
    'ov-dial': OvDial;
    'ov-donut': OvDonut;
    'ov-dose': OvDose;
    'ov-downlink': OvDownlink;
    'ov-ecg': OvEcg;
    'ov-endurance': OvEndurance;
    'ov-fan': OvFan;
    'ov-fault': OvFault;
    'ov-field': OvField;
    'ov-flap': OvFlap;
    'ov-gauge': OvGauge;
    'ov-geomap': OvGeomap;
    'ov-graph': OvGraph;
    'ov-node': OvNode;
    'ov-socket': OvSocket;
    'ov-link': OvLink;
    'ov-grid': OvGrid;
    'ov-histogram': OvHistogram;
    'ov-hold': OvHold;
    'ov-horizon': OvHorizon;
    'ov-icon': OvIcon;
    'ov-ladder': OvLadder;
    'ov-likelihood': OvLikelihood;
    'ov-locator': OvLocator;
    'ov-log': OvLog;
    'ov-map': OvMap;
    'ov-match': OvMatch;
    'ov-menu': OvMenu;
    'ov-modal': OvModal;
    'ov-mosaic': OvMosaic;
    'ov-orbit': OvOrbit;
    'ov-ornament': OvOrnament;
    'ov-plate': OvPlate;
    'ov-player': OvPlayer;
    'ov-polygon': OvPolygon;
    'ov-position': OvPosition;
    'ov-procedure': OvProcedure;
    'ov-quorum': OvQuorum;
    'ov-radar': OvRadar;
    'ov-rangebar': OvRangebar;
    'ov-reticle': OvReticle;
    'ov-schematic': OvSchematic;
    'ov-scope': OvScope;
    'ov-score': OvScore;
    'ov-segment': OvSegment;
    'ov-sequence': OvSequence;
    'ov-sound-switch': OvSoundSwitch;
    'ov-split': OvSplit;
    'ov-station': OvStation;
    'ov-switch': OvSwitch;
    'ov-table': OvTable;
    'ov-tactical': OvTactical;
    'ov-term': OvTerm;
    'ov-text': OvText;
    'ov-timeline': OvTimeline;
    'ov-timestack': OvTimestack;
    'ov-topology': OvTopology;
    'ov-track': OvTrack;
    'ov-transport': OvTransport;
    'ov-tree': OvTree;
    'ov-verifier': OvVerifier;
    'ov-vitals': OvVitals;
    'ov-waterfall': OvWaterfall;
    'ov-wave': OvWave;
    'ov-window': OvWindow;
    'ov-wireframe': OvWireframe;
  }
}
