#!/usr/bin/env python3
"""Generate the ov-geomap mutants: one copy per refusal, each broken on purpose.
The gate MUST go red against every one. Run from tools/geomap-test/: python3 mut/make.py

A refusal that lives in ov-geo.js (shared with ov-tactical) is broken in a copy
of ov-geo.js under mut/lib/, which that mutant imports instead of the real one.
lib/ is not matched by the runner's mut/*.js, so a copy is never run as an element.
"""
import os

os.makedirs('mut/lib', exist_ok=True)
EL = open('../../src/ov-geomap.js').read()
GEO = open('../../src/ov-geo.js').read()
HEAD = "/* MUTANT: one refusal broken on purpose. Generated by mut/make.py. */\n"


def element(geo_path):
    s = EL.replace("from './ov-core.js'", "from '../../../src/ov-core.js'")
    s = s.replace("import './ov-source.js';", "import '../../../src/ov-source.js';")
    assert s.count("from './ov-geo.js'") == 1
    return s.replace("from './ov-geo.js'", f"from '{geo_path}'")


def mut(name, old, new):
    assert EL.count(old) == 1, (name, EL.count(old))
    open(f'mut/{name}.js', 'w').write(HEAD + element('../../../src/ov-geo.js').replace(old, new))
    print('wrote', name)


def geomut(name, old, new):
    assert GEO.count(old) == 1, (name, GEO.count(old))
    open(f'mut/lib/{name}.js', 'w').write(HEAD + GEO.replace(old, new))
    open(f'mut/{name}.js', 'w').write(HEAD + element(f'./lib/{name}.js'))
    print('wrote', name, '(ov-geo.js)')


# a: one report is called live, though nothing can have moved.
geomut('a-one-report-live', "  return moved ? 'live' : 'held';", "  return 'live'; /* MUTANT */")
# b: a fix never goes stale.
geomut('b-never-stale', "  if (age > fresh) return 'stale';", "  /* MUTANT */")
# c: a fix with no time is judged by its missing time as fresh.
geomut('c-undated-fresh', "  if (pos.at === null || pos.at === undefined || pos.at === '' || !Number.isFinite(at)) return 'undated';", "  /* MUTANT */")
# d: a time in the future is trusted.
geomut('d-ahead-trusted', "  if (age < -AHEAD_S) return 'ahead';", "  /* MUTANT */")
# e: the route is drawn along the straight line instead of the great circle.
geomut('e-straight-route', "(_, i) => toLL(slerp(a, b, i / n)));",
       "(_, i) => ({ lat: from.lat + (to.lat - from.lat) * i / n, lon: from.lon + (to.lon - from.lon) * i / n })); /* MUTANT */")
# f: a fresh fix prints an age, which stops counting the moment reports stop.
geomut('f-ticking-age', "    default: return `FIX ${clock(at)}`;", "    default: return `FIX ${Math.round(age)} S`; /* MUTANT */")
# g: no timer is ever set, so a fix goes stale only when something else repaints.
geomut('g-no-timer', "  return Number.isFinite(due) ? due : null;", "  return null; /* MUTANT */")
# h: any fix pings, moving or not.
mut('h-ping-any', "(state === 'live' ? `<circle class=\"ov-geomap__ping\"", "(state !== 'plan' ? `<circle class=\"ov-geomap__ping\"")
# i: a fix far off its route is not said to be.
mut('i-off-route-silent', "if (o.xtKm > 25) words.push(`${fmtKm(o.xtKm)} OFF ROUTE`);", "/* MUTANT */")
# j: outlines asked for and absent are not said.
mut('j-countries-silent', "if (nope) refuse(esc(nope));", "/* MUTANT */")
# k: rings over the antimeridian are not unwrapped, and fill a stripe across the map.
mut('k-seam-stripe', "        while (x - lx > 180) x -= 360;\n        while (lx - x > 180) x += 360;", "        /* MUTANT */")
# l: routes without both ends vanish without a word.
mut('l-routes-dropped', "if (ctx.unplaced) refuse(", "if (false) refuse(")
# m: the screen line is labelled with the great circle's length.
mut('m-screen-line-unmeasured', "words.push(`SCREEN LINE ${fmtKm(km)}, +${fmtKm(km - gc.km)}`);",
    "words.push(`SCREEN LINE ${fmtKm(gc.km)}, +0 km`); /* MUTANT */")
# n: the head is snapped onto the route.
mut('n-head-snapped', "      at = ll(r.pos);", "      at = gc.points[Math.round(onRoute(gc, ll(r.pos)).frac * gc.n)]; /* MUTANT */")
# o: a source that never answers reads as an empty sky.
mut('o-no-feed-silent', "if (this.getAttribute('source') && !this._heard) refuse(", "if (false) refuse(")
