#!/usr/bin/env python3
"""Generate the ov-ecg mutants: one copy per refusal, each broken on purpose.
The gate MUST go red against every one. Run from tools/ecg-test/: python3 mut/make.py
"""
src = open('../../src/ov-ecg.js').read().replace("from './ov-core.js'", "from '../../../src/ov-core.js'")
head = "/* MUTANT: one refusal broken on purpose. Generated by mut/make.py. */\n"
def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)
# a: the arrival hook's no-op is kept, so only the first stale timer ever runs.
mut('a-hook-kept', "    if (!started) this._unarrive = off;", "    this._unarrive = off; /* MUTANT */")
# b: the headline. A disconnected lead is drawn as a flat line.
mut('b-flat-line', "if (this.hasAttribute('leads-off')) return 'leads-off';", "if (false) return 'leads-off'; /* MUTANT */")
# c: a stopped signal keeps reading as live.
mut('c-stopped-live', "if ((now - this._lastFeed) / 1000 > this.maxAge()) return 'stopped';", "if (false) return 'stopped'; /* MUTANT */")
# d: feeding stores samples and draws nothing, so the sweep never moves.
mut('d-feed-no-draw', "isSeen(this) && this._lastFeed - this._lastDraw >= FRAME_MS) this.draw();", "false) this.draw(); /* MUTANT */")
# e: a flat trace nobody called keeps its rate.
mut('e-flat-keeps-rate', "const shown = (state === 'live' || state === 'asystole') && rate !== null;", "const shown = (state === 'live' || state === 'asystole' || state === 'flat') && rate !== null; /* MUTANT */")
# f: an asystole call does not alarm.
mut('f-asystole-silent', "const alarm = state === 'asystole' || ", "const alarm = false || /* MUTANT */ ")
# g: paused monitoring draws the last trace like a flat heart.
mut('g-paused-draws', "if (this.hasAttribute('paused')) return 'paused';", "if (false) return 'paused'; /* MUTANT */")
