#!/usr/bin/env python3
"""Capture the ov-chart that HAD the bug, as the thing the gate must fail on.

🔴 THE MUTANT IS THE ORIGINAL. Everywhere else in this tree a mutant is the
current element with one refusal broken on purpose. Here the bug is already
recorded in history, so the honest mutant is the file as it actually was at
07ede6b: a chart with no stale state at all, where `data-ov-stale` is only ever
removed and never set. A gate for a fix should be run against the code that had
the fault, or it is only testing that the fix agrees with itself.

Run from tools/chart-stale-test/: python3 mut/make.py
"""
import subprocess

BEFORE = '07ede6b'
src = subprocess.run(['git', 'show', f'{BEFORE}:src/ov-chart.js'],
                     capture_output=True, text=True, check=True).stdout
head = (f"/* THE ELEMENT AS IT WAS AT {BEFORE}, before rule 5. `data-ov-stale` is only\n"
        " * ever removed here and never set, so a stopped feed keeps its last trace\n"
        " * unmarked. The gate MUST go red against this file: that is what proves it\n"
        " * tests the bug rather than the fix. Generated by mut/make.py.\n */\n")
# The file as it was also carried pointers to private working notes, which the kit
# export cannot carry. Comments only; the code stays exactly as it was.
for a, b in (("fui" + "-lab's strongest cross-cutting result was", 'the strongest cross-cutting result behind this kit was'),
             ('specimens found it independently', 'separate tests found it'),
             (' (PERF' + '.md)', ''),
             ("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(a, b)
open('mut/a-no-stale-state.js', 'w').write(head + src)
print('wrote a-no-stale-state (ov-chart as at %s)' % BEFORE)
