#!/usr/bin/env python3
"""Generate the ov-score mutants: one copy per refusal, each broken on purpose.
The gate MUST go red against every one.

Run from tools/score-test/: python3 mut/make.py
"""
src = open('../../src/ov-score.js').read()
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)
head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. A missing parameter scores 0, which is the BEST score it
# could have, so the absent observation silently improves the patient.
mut('a-missing-scores-zero',
    "        score: missing ? null : (Number.isFinite(score) ? score : null),",
    "        score: missing ? 0 : (Number.isFinite(score) ? score : null),"
    "  // MUTANT: absent counts as best")

# b: the two absences collapse into one, so an unobtainable measure is a gap.
mut('b-absences-alike',
    "        if (ABSENT[p.missing].urgent) r.urgent.push(p.name);",
    "        if (false) r.urgent.push(p.name);  // MUTANT: a gap is a gap")

# c: a single red is folded into the total and never surfaced.
mut('c-red-hides',
    "      if (p.score >= red) r.singleRed.push(p.name);",
    "      if (false) r.singleRed.push(p.name);  // MUTANT: the total speaks for it")

# d: scale 2 accepted with nobody recorded.
mut('d-unsigned-scale',
    "    r.scaleRefused = rd.scale === 2 && !rd.scaleBy;",
    "    r.scaleRefused = false;  // MUTANT: any scale 2 is fine")

# e: oxygen with no paperwork passes quietly.
mut('e-oxygen-undocumented',
    "    r.oxygenUndocumented = rd.oxygen.on && !(rd.oxygen.rate && rd.oxygen.device);",
    "    r.oxygenUndocumented = false;  // MUTANT: the weighting needs no evidence")

# f: an incomplete total is presented as complete.
mut('f-incomplete-passes',
    "    r.state = r.incomplete.length ? 'incomplete' : 'complete';",
    "    r.state = 'complete';  // MUTANT: every total is a whole one")
