#!/usr/bin/env python3
"""Generate the ov-datablock mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

🔴 GENERATED, NOT HAND-WRITTEN, so a mutant can only ever differ from src by
its one intended change.

Run from tools/datablock-test/: python3 mut/make.py
"""
src = open('../../src/ov-datablock.js').read()
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. A coasting track keeps its callsign.
mut('a-coast-keeps-identity',
    "    setText(this.$.callsign, r.coasting ? `CST ${r.coastAge === null ? 'NO MEASURED FIX' : span(r.coastAge)}` : r.callsign || 'NO CALLSIGN');",
    "    setText(this.$.callsign, r.callsign || 'NO CALLSIGN');  // MUTANT: identity through a coast")

# b: coast-after is ignored, so a stale track stays live.
mut('b-coast-after-ignored',
    "    const selfCoast = limit !== null && (!lastMeasured || lastMeasured.age > limit);",
    "    const selfCoast = false;  // MUTANT: trust the status bit alone")

# c: a derived level takes the measured slot.
mut('c-derived-as-measured',
    "    if (repValue !== null && src && src[0] !== 'derived') {",
    "    if (repValue !== null && src) {  // MUTANT: a default height is a measured level")

# d: after a start from coast the level is shown as valid.
mut('d-unvalidated-dropped',
    "      levels.unvalidated = (st.fromCoast === true || rep.validated === false) && rep.validated !== true;",
    "      levels.unvalidated = false;  // MUTANT")

# e: an unsupported sensor shows its meaningless age as fresh.
mut('e-unsupported-fresh',
    "      if (s.supported === false) return { kind: s.kind, word: 'n/a', state: 'unsupported' };",
    "      // MUTANT: the default age counts as fresh")

# f: a selected level stands in for the read-back.
mut('f-selected-as-readback',
    "      cleared: num(L.cleared?.value), readback: L.cleared?.readback === true, selected: num(L.selected?.value),",
    "      cleared: num(L.cleared?.value), readback: L.cleared?.readback === true || num(L.selected?.value) === num(L.cleared?.value), selected: num(L.selected?.value),  // MUTANT")
