/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-annunciator.js';
import { wrap } from './runtime.js';

export const OvAnnunciator = wrap('ov-annunciator', ["conditions"], {acknowledge: 'ov:acknowledge', annunciate: 'ov:annunciate', shelve: 'ov:shelve'});
