/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-clearance.js';
import { wrap } from './runtime.js';

export const OvClearance = wrap('ov-clearance', ["pick"], {});
