/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-ecg.js';
import { wrap } from './runtime.js';

export const OvEcg = wrap('ov-ecg', ["samples"], {ecg: 'ov:ecg'});
