/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-likelihood.js';
import { wrap } from './runtime.js';

export const OvLikelihood = wrap('ov-likelihood', ["finding"], {});
