/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-player.js';
import { wrap } from './runtime.js';

export const OvPlayer = wrap('ov-player', ["media"], {player: 'ov:player'});
