/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-position.js';
import { wrap } from './runtime.js';

export const OvPosition = wrap('ov-position', ["fix"], {});
