/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-procedure.js';
import { wrap } from './runtime.js';

export const OvProcedure = wrap('ov-procedure', ["sensed"], {claim: 'ov:claim', complete: 'ov:complete', refuse: 'ov:refuse'});
