/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-quorum.js';
import { wrap } from './runtime.js';

export const OvQuorum = wrap('ov-quorum', ["readings"], {quorum: 'ov:quorum'});
