/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-rangebar.js';
import { wrap } from './runtime.js';

export const OvRangebar = wrap('ov-rangebar', ["channels"], {});
