/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-sequence.js';
import { wrap } from './runtime.js';

export const OvSequence = wrap('ov-sequence', ["sequence"], {});
