/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-solid.js';
import { wrap } from './runtime.js';

export const OvSolid = wrap('ov-solid', ["mesh", "survey"], {});
