/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-switch.js';
import { wrap } from './runtime.js';

export const OvSwitch = wrap('ov-switch', ["reading", "talkback"], {arm: 'ov:arm', command: 'ov:command', safe: 'ov:safe'});
