/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-timeline.js';
import { wrap } from './runtime.js';

export const OvTimeline = wrap('ov-timeline', ["spans"], {seek: 'ov:seek', solo: 'ov:solo'});
