/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-timestack.js';
import { wrap } from './runtime.js';

export const OvTimestack = wrap('ov-timestack', ["stamp"], {});
