/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-verifier.js';
import { wrap } from './runtime.js';

export const OvVerifier = wrap('ov-verifier', ["commands"], {verify: 'ov:verify'});
