/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-window.js';
import { wrap } from './runtime.js';

export const OvWindow = wrap('ov-window', [], {resize: 'ov:resize'});
