/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import { defineComponent, h, onBeforeUnmount, onMounted, ref, watchEffect } from 'vue';

/* 🔴 THE WRAPPER SETS ATTRIBUTES ITSELF, AND THIS IS THE WHOLE REASON IT IS
 * NOT A ONE-LINER.
 *
 * All three frameworks apply the same heuristic to a custom element: if the
 * prop NAME EXISTS ON THE ELEMENT, set it as a property, otherwise set an
 * attribute. This kit has 47 GETTER-ONLY properties across 21 elements, and
 * many of them share a name with a real attribute: digits, step, lat, lon,
 * range, span, period, rings, hold, sweeps, floor, traces, at, duration, mode.
 *
 * So `<OvSegment digits="4" />` made React find `digits` on the element, try to
 * assign it, and throw "Cannot set property digits of #<OvSegment> which has
 * only a getter". That did not degrade: it took down the ENTIRE React tree, and
 * the same heuristic exists in Vue and in Svelte's custom-element path.
 *
 * Passing attributes through the framework is therefore not an option, and
 * neither is a list of which names are safe, since that list would rot against
 * src/. The wrapper hands the framework nothing but a ref and applies every
 * attribute itself, which is deterministic and identical on React 18 and 19.
 */
function applyAttrs(el, next, prev) {
  for (const key of Object.keys(prev)) {
    if (!(key in next)) el.removeAttribute(key === 'className' ? 'class' : key);
  }
  for (const [key, value] of Object.entries(next)) {
    const name = key === 'className' ? 'class' : key;
    if (name === 'style' && value && typeof value === 'object') {
      Object.assign(el.style, value);
      continue;
    }
    if (value === null || value === undefined || value === false) el.removeAttribute(name);
    else if (value === true) el.setAttribute(name, '');
    else el.setAttribute(name, String(value));
  }
}


/* Vue is the only one of the three that CAN bind `ov:commit` in a template,
 * as `@ov:commit`. The wrapper still exists so the three spellings match, so
 * readings are set as properties rather than attributes, and so the event
 * arrives under a name that looks like every other Vue event.
 */
export function wrap(tag, propNames, events) {
  return defineComponent({
    name: tag,
    /* undefined default, deliberately: it means "not driving this property",
     * which the reading protocol distinguishes from null, a dropout. */
    props: Object.fromEntries(propNames.map((n) => [n, { default: undefined }])),
    emits: Object.keys(events),
    setup(props, { attrs, slots, emit }) {
      const host = ref(null);

      let lastAttrs = {};
      watchEffect(() => {
        const el = host.value;
        if (!el) return;
        applyAttrs(el, attrs, lastAttrs);
        lastAttrs = { ...attrs };
        for (const name of propNames) {
          if (props[name] !== undefined && el[name] !== props[name]) {
            el[name] = props[name];
          }
        }
      });

      let off = [];
      onMounted(() => {
        const el = host.value;
        if (!el) return;
        off = Object.entries(events).map(([name, type]) => {
          const handler = (event) => emit(name, event);
          el.addEventListener(type, handler);
          return () => el.removeEventListener(type, handler);
        });
      });
      onBeforeUnmount(() => { off.forEach((f) => f()); off = []; });

      /* ref only; every attribute is applied by applyAttrs above. */
      return () => h(tag, { ref: host },
        slots.default ? slots.default() : undefined);
    },
  });
}
