#!/usr/bin/env python3
"""Generate the ov-vitals mutants: one copy per refusal, each broken on purpose.
The gate MUST go red against every one.

Run from tools/vitals-test/: python3 mut/make.py
"""
src = open('../../src/ov-vitals.js').read()
src = src.replace("from './ov-core.js'", "from '../../../src/ov-core.js'")
head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. A fresh blood pressure is drawn in the live form.
mut('a-nibp-live',
    "    t.mark = t.age >= agedS ? 'aged' : 'taken';",
    "    t.mark = t.age >= agedS ? 'aged' : 'live';  // MUTANT")

# b: a blood pressure never ages out: an hour-old one keeps its numbers.
mut('b-nibp-never-invalid',
    "    if (t.age >= NBP_INVALID_S) {",
    "    if (false) {  // MUTANT")

# c: an interrupting SpO2 INOP keeps the last number.
mut('c-spo2-keeps-number',
    "    if (Object.hasOwn(SPO2_INTERRUPT, inop)) { t.words = SPO2_INTERRUPT[inop]; return; }",
    "    if (false) { return; }  // MUTANT")

# d: a rate with no source is called HR and trusted.
mut('d-source-assumed',
    "    else { t.label = 'RATE'; t.src = 'SOURCE NOT STATED'; }",
    "    else { t.label = 'HR'; t.src = 'ECG'; }  // MUTANT")

# e: a pleth pulse ignores its own sensor.
mut('e-pleth-ignores-sensor',
    "    if ((src === 'pleth' || src === 'spo2') && spo2 && Object.hasOwn(SPO2_INTERRUPT, spo2.inop)) {",
    "    if (false) {  // MUTANT")

# f: nothing goes stale.
mut('f-never-stale',
    "      if (t.age > staleS) {",
    "      if (false /* MUTANT: never stale */) {")

# g: alarms off is not a note: the status reads ok.
mut('g-alarms-off-ok',
    "    if (on.some((t) => t.alarmsOff || ",
    "    if (on.some((t) => false || ")

# i: the trend bridges every gap, so a silence looks like steady readings.
mut('i-trend-bridges-gaps',
    "          const join = prev && e.t - prev.t <= gapMs && e.s === prev.s;",
    "          const join = d !== ''; /* MUTANT */")

# j: blood pressures are drawn as a joined line like a continuous number.
mut('j-nibp-joined',
    "      if (t.key === 'nibp') {\n        // Refusal: one bar per cuff reading, never joined.",
    "      if (false) { /* MUTANT */")

# h: one limit is enough for an alarm claim.
mut('h-one-limit-alarms',
    "    if (fin(L[0]) && fin(L[1])) t.limits = [val(L[0]), val(L[1])];",
    "    if (fin(L[0])) t.limits = [val(L[0]), fin(L[1]) ? val(L[1]) : Infinity];  // MUTANT")
