#!/usr/bin/env python3
"""Generate the ov-tactical mutants: one copy per refusal, each broken on purpose.
The gate MUST go red against every one. Run from tools/tactical-test/: python3 mut/make.py

A refusal that lives in ov-geo.js (shared with ov-geomap) is broken in a copy
of ov-geo.js under mut/lib/, which that mutant imports instead of the real one.
lib/ is not matched by the runner's mut/*.js, so a copy is never run as an element.
"""
import os

os.makedirs('mut/lib', exist_ok=True)
EL = open('../../src/ov-tactical.js').read()
GEO = open('../../src/ov-geo.js').read()
HEAD = "/* MUTANT: one refusal broken on purpose. Generated by mut/make.py. */\n"


def element(geo_path):
    s = EL.replace("from './ov-core.js'", "from '../../../src/ov-core.js'")
    s = s.replace("import './ov-source.js';", "import '../../../src/ov-source.js';")
    assert s.count("from './ov-geo.js'") == 1
    return s.replace("from './ov-geo.js'", f"from '{geo_path}'")


def mut(name, old, new):
    assert EL.count(old) == 1, (name, EL.count(old))
    open(f'mut/{name}.js', 'w').write(HEAD + element('../../../src/ov-geo.js').replace(old, new))
    print('wrote', name)


def geomut(name, old, new):
    assert GEO.count(old) == 1, (name, GEO.count(old))
    open(f'mut/lib/{name}.js', 'w').write(HEAD + GEO.replace(old, new))
    open(f'mut/{name}.js', 'w').write(HEAD + element(f'./lib/{name}.js'))
    print('wrote', name, '(ov-geo.js)')


# a: the headline. The screen circle is assumed to reach the ring everywhere.
mut('a-circle-assumed', "const nKm = up && Math.hypot(...up), eKm = right && Math.hypot(...right);",
    "const nKm = ring, eKm = ring; /* MUTANT */")
# b: pitch is not capped.
mut('b-pitch-uncapped', "get pitch() { return Math.max(0, Math.min(PITCH_MAX, this.num(this.getAttribute('pitch'), 30))); }",
    "get pitch() { return Math.max(0, this.num(this.getAttribute('pitch'), 30)); } /* MUTANT */")
# c: a stale track still draws its heading.
mut('c-stale-heading', "const fine = state === 'live' || state === 'held';", "const fine = true; /* MUTANT */")
# d: the heading line is a fixed length on the glass, not a lead on the ground.
mut('d-lead-on-glass', "spd * 1.852 * (LEAD_MIN / 60)", "60 /* MUTANT */")
# e: tracks off the view or without a position vanish without a word.
mut('e-tracks-dropped', "if (off || nofix) refuse(", "if (false) refuse(")
# f: the plain wheel is taken, trapping the page's scroll.
mut('f-wheel-trap', "if (!this.hasAttribute('orbit') || !(e.ctrlKey || e.metaKey)) return;",
    "if (!this.hasAttribute('orbit')) return; /* MUTANT */")
# g: keys move the camera without `orbit`.
mut('g-orbit-always', "    if (!this.hasAttribute('orbit')) return;\n    const step", "    const step")
# h: one report is called live (in ov-geo.js).
geomut('h-one-report-live', "  return moved ? 'live' : 'held';", "  return 'live'; /* MUTANT */")
# i: no timer is ever set (in ov-geo.js).
geomut('i-no-timer', "  return Number.isFinite(due) ? due : null;", "  return null; /* MUTANT */")
# j: outlines asked for and absent are not said.
mut('j-countries-silent', "if (nope) refuse(esc(nope));", "/* MUTANT */")
# k: a stale fix reads like a fresh one (in ov-geo.js).
geomut('k-stale-reads-fresh', "    case 'stale': return age < 120",
       "    case 'stale': return `FIX ${clock(at)}`; /* MUTANT */\n    case 'unused': return age < 120")
