#!/usr/bin/env python3
"""Generate the ov-balance mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

A green gate run only proves the harness runs; these prove it can fail.
Run from tools/balance-test/: python3 mut/make.py
"""
src = open('../../src/ov-balance.js').read()
# 🔴 A MUTANT LIVES IN mut/, TWO LEVELS BELOW src/, so the element's own
# relative imports have to be rewritten or every mutant dies at import time -
# which the gate reports as a THROW, not as the refusal failing. A mutant that
# cannot load proves nothing about the refusal it was made to break.
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline, as `frozen` would do it. Only a level that has stopped
# moving is ever disputed, which is exactly the case Texas City was not.
mut('a-flatline-only',
    "    r.over = Math.abs(r.residual) > r.tol;",
    "    r.over = Math.abs(r.residual) > r.tol && Math.abs(r.dLevel) < 1e-9;  "
    "// MUTANT: only a stuck level counts")

# b: an unknown rate treated as no flow, so the check runs on a partial set.
mut('b-zero-for-unknown',
    "        rate: s.status === 'failed' || !Number.isFinite(rate) ? null : rate,",
    "        rate: s.status === 'failed' || !Number.isFinite(rate) ? 0 : rate,  "
    "// MUTANT: no rate means no flow")

# c: the span is the whole vessel, so nothing is ever drawn as unmeasured.
mut('c-span-is-vessel',
    "      spanMax: num(this.getAttribute('span-max')),",
    "      spanMax: num(this.getAttribute('height')),  // MUTANT: the span is the vessel")

# d: a balance struck over whatever history happens to exist.
mut('d-short-window-judged',
    "    if (r.windowHave < win) {",
    "    if (false && r.windowHave < win) {  // MUTANT: judge a part-filled window")

# e: the tolerance defaulted instead of refused, so the element always judges.
mut('e-default-tolerance',
    "    if (!finite(p.meterError) || p.meterError < 0 || !finite(p.levelError) || p.levelError < 0) {\n"
    "      r.state = 'unruled';\n"
    "      r.why = 'NO TOLERANCE DECLARED · meter-error and level-error are required';\n"
    "      return done();\n"
    "    }",
    "    // MUTANT: a tolerance nobody declared, invented here.\n"
    "    if (!finite(p.meterError) || p.meterError < 0) p.meterError = 1;\n"
    "    if (!finite(p.levelError) || p.levelError < 0) p.levelError = 0.5;")
