/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-allocator.js';
import { wrap } from './runtime.js';

export const OvAllocator = wrap('ov-allocator', ["readback"], {onAllocate: 'ov:allocate', onRefuse: 'ov:refuse'});
