/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-annunciator.js';
import { wrap } from './runtime.js';

export const OvAnnunciator = wrap('ov-annunciator', ["conditions"], {onAcknowledge: 'ov:acknowledge', onAnnunciate: 'ov:annunciate', onShelve: 'ov:shelve'});
