/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-authority.js';
import { wrap } from './runtime.js';

export const OvAuthority = wrap('ov-authority', ["picture"], {onAuthority: 'ov:authority'});
