/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-baseline.js';
import { wrap } from './runtime.js';

export const OvBaseline = wrap('ov-baseline', ["samples"], {onBaseline: 'ov:baseline', onRefuse: 'ov:refuse'});
