/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-cli.js';
import { wrap } from './runtime.js';

export const OvCli = wrap('ov-cli', [], {onCommand: 'ov:command'});
