/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-coverage.js';
import { wrap } from './runtime.js';

export const OvCoverage = wrap('ov-coverage', ["coverage"], {});
