/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-consistency.js';
import { wrap } from './runtime.js';

export const OvConsistency = wrap('ov-consistency', ["watch"], {});
