/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-countdown.js';
import { wrap } from './runtime.js';

export const OvCountdown = wrap('ov-countdown', ["clock"], {onClock: 'ov:clock'});
