/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-datablock.js';
import { wrap } from './runtime.js';

export const OvDatablock = wrap('ov-datablock', ["track"], {onDatablock: 'ov:datablock'});
