/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-dial.js';
import { wrap } from './runtime.js';

export const OvDial = wrap('ov-dial', [], {onChange: 'ov:change'});
