/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-downlink.js';
import { wrap } from './runtime.js';

export const OvDownlink = wrap('ov-downlink', [], {onSignal: 'ov:signal'});
