/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-geomap.js';
import { wrap } from './runtime.js';

export const OvGeomap = wrap('ov-geomap', ["countriesData", "routes"], {});
