/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-histogram.js';
import { wrap } from './runtime.js';

export const OvHistogram = wrap('ov-histogram', ["histogram"], {});
