/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-hold.js';
import { wrap } from './runtime.js';

export const OvHold = wrap('ov-hold', [], {onCancel: 'ov:cancel', onCommit: 'ov:commit'});
