/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-plate.js';
import { wrap } from './runtime.js';

export const OvPlate = wrap('ov-plate', ["detections"], {onView: 'ov:view'});
