/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-procedure.js';
import { wrap } from './runtime.js';

export const OvProcedure = wrap('ov-procedure', ["sensed"], {onClaim: 'ov:claim', onComplete: 'ov:complete', onRefuse: 'ov:refuse'});
