/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-schematic.js';
import { wrap } from './runtime.js';

export const OvSchematic = wrap('ov-schematic', ["plan", "states"], {});
