/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-sound-switch.js';
import { wrap } from './runtime.js';

export const OvSoundSwitch = wrap('ov-sound-switch', [], {});
