/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-station.js';
import { wrap } from './runtime.js';

export const OvStation = wrap('ov-station', ["observation"], {onStation: 'ov:station'});
