/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-switch.js';
import { wrap } from './runtime.js';

export const OvSwitch = wrap('ov-switch', ["reading", "talkback"], {onArm: 'ov:arm', onCommand: 'ov:command', onSafe: 'ov:safe'});
