/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-tactical.js';
import { wrap } from './runtime.js';

export const OvTactical = wrap('ov-tactical', ["countriesData", "data"], {onView: 'ov:view'});
