/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-table.js';
import { wrap } from './runtime.js';

export const OvTable = wrap('ov-table', ["cols", "rows"], {onReorder: 'ov:reorder'});
