/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-topology.js';
import { wrap } from './runtime.js';

export const OvTopology = wrap('ov-topology', ["topology"], {});
