/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-tree.js';
import { wrap } from './runtime.js';

export const OvTree = wrap('ov-tree', [], {onReorder: 'ov:reorder'});
