/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-transport.js';
import { wrap } from './runtime.js';

export const OvTransport = wrap('ov-transport', [], {onPause: 'ov:pause', onPlay: 'ov:play', onSeek: 'ov:seek'});
