/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-vitals.js';
import { wrap } from './runtime.js';

export const OvVitals = wrap('ov-vitals', ["vitals"], {onVitals: 'ov:vitals'});
