/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-watchdog.js';
import { wrap } from './runtime.js';

export const OvWatchdog = wrap('ov-watchdog', [], {onWatchdog: 'ov:watchdog'});
