/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import '../ov-wireframe.js';
import { wrap } from './runtime.js';

export const OvWireframe = wrap('ov-wireframe', ["figures", "survey"], {});
