/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import { createElement, forwardRef, useEffect, useLayoutEffect, useRef } from 'react';

/* useLayoutEffect warns during SSR, where there is no layout to read. */
const useIso = typeof document === 'undefined' ? useEffect : useLayoutEffect;

/* 🔴 THE WRAPPER SETS ATTRIBUTES ITSELF, AND THIS IS THE WHOLE REASON IT IS
 * NOT A ONE-LINER.
 *
 * All three frameworks apply the same heuristic to a custom element: if the
 * prop NAME EXISTS ON THE ELEMENT, set it as a property, otherwise set an
 * attribute. This kit has 47 GETTER-ONLY properties across 21 elements, and
 * many of them share a name with a real attribute: digits, step, lat, lon,
 * range, span, period, rings, hold, sweeps, floor, traces, at, duration, mode.
 *
 * So `<OvSegment digits="4" />` made React find `digits` on the element, try to
 * assign it, and throw "Cannot set property digits of #<OvSegment> which has
 * only a getter". That did not degrade: it took down the ENTIRE React tree, and
 * the same heuristic exists in Vue and in Svelte's custom-element path.
 *
 * Passing attributes through the framework is therefore not an option, and
 * neither is a list of which names are safe, since that list would rot against
 * src/. The wrapper hands the framework nothing but a ref and applies every
 * attribute itself, which is deterministic and identical on React 18 and 19.
 */
function applyAttrs(el, next, prev) {
  for (const key of Object.keys(prev)) {
    if (!(key in next)) el.removeAttribute(key === 'className' ? 'class' : key);
  }
  for (const [key, value] of Object.entries(next)) {
    const name = key === 'className' ? 'class' : key;
    if (name === 'style' && value && typeof value === 'object') {
      Object.assign(el.style, value);
      continue;
    }
    if (value === null || value === undefined || value === false) el.removeAttribute(name);
    else if (value === true) el.setAttribute(name, '');
    else el.setAttribute(name, String(value));
  }
}


/* Build one React component around one custom element.
 *
 * ⚠️ Properties are set through a ref rather than passed as JSX attributes,
 * and not because React 19 cannot do it. React 19 WILL set a property when the
 * name exists on the element, but that check happens when React renders, and
 * whether the element has upgraded by then depends on module and network
 * order. When it has not, the value silently becomes an ATTRIBUTE instead:
 * an array stringifies to "1,2,3" and a null becomes the word "null", which
 * the reading protocol reads as a value rather than a dropout. Setting through
 * the ref is order-independent and behaves the same on React 18.
 */
export function wrap(tag, propNames, events) {
  const Component = forwardRef(function OverscanElement(props, forwarded) {
    const host = useRef(null);
    const { children, ...rest } = props;

    const values = {};
    const handlers = {};
    const attrs = {};
    for (const [key, value] of Object.entries(rest)) {
      if (propNames.includes(key)) values[key] = value;
      else if (key in events) handlers[key] = value;
      else attrs[key] = value;
    }

    /* Latest handlers without re-binding listeners on every render. */
    const latest = useRef(handlers);
    latest.current = handlers;

    const lastAttrs = useRef({});

    useIso(() => {
      const el = host.current;
      if (!el) return;
      applyAttrs(el, attrs, lastAttrs.current);
      lastAttrs.current = attrs;
      for (const [key, value] of Object.entries(values)) {
        /* undefined means "not driving this property", which is NOT the same
         * as null. Writing undefined would clear a value the markup set. */
        if (value !== undefined && el[key] !== value) el[key] = value;
      }
    });

    useEffect(() => {
      const el = host.current;
      if (!el) return undefined;
      const off = Object.entries(events).map(([key, type]) => {
        const handler = (event) => {
          const fn = latest.current[key];
          if (typeof fn === 'function') fn(event);
        };
        el.addEventListener(type, handler);
        return () => el.removeEventListener(type, handler);
      });
      return () => off.forEach((f) => f());
    }, []);

    /* Only a ref. Nothing else is handed to React: see applyAttrs. */
    return createElement(tag, {
      ref: (node) => {
        host.current = node;
        if (typeof forwarded === 'function') forwarded(node);
        else if (forwarded) forwarded.current = node;
      },
    }, children);
  });
  Component.displayName = tag;
  return Component;
}
