#!/usr/bin/env python3
"""Generate the ov-player mutants: one copy per refusal, each broken on purpose.
The gate MUST go red against every one. Run from tools/player-test/: python3 mut/make.py
"""
src = open('../../src/ov-player.js').read().replace("from './ov-core.js'", "from '../../../src/ov-core.js'")
head = "/* MUTANT: one refusal broken on purpose. Generated by mut/make.py. */\n"
def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)
# a: the arrival hook's no-op is kept, so only the first freeze timer ever runs.
mut('a-hook-kept', "    if (!started) this._unarrive = off;", "    this._unarrive = off; /* MUTANT */")
# b: the headline. Buffered ranges are drawn as played.
mut('b-buffered-played', "const playedHtml = segs(ranges(m.played), 'ov-player__seg');", "const playedHtml = segs(ranges(m.buffered), 'ov-player__seg'); /* MUTANT */")
# c: a clock that stopped still reads as playing.
mut('c-frozen-playing', "if (this._lastAdvance !== null && now - this._lastAdvance > freezeMs) return 'frozen';", "if (false) return 'frozen'; /* MUTANT */")
# d: LIVE is claimed however far behind the edge.
mut('d-behind-live', "const liveClaim = isLive && state === 'playing' && nearEdge && !edgeStale;", "const liveClaim = isLive && state === 'playing' && !edgeStale; /* MUTANT */")
# e: stalls are never counted.
mut('e-stalls-uncounted', "      this._stalls += 1;", "      /* MUTANT */")
# f: dropped frames are not shown.
mut('f-drops-hidden', "? `DROPPED ${q.droppedVideoFrames} / ${q.totalVideoFrames}`", "? '' /* MUTANT */")
# g: too little data is drawn as playing.
mut('g-waiting-playing', "if (Number(m.readyState) < HAVE_FUTURE_DATA) return this._netStalled ? 'stalled' : 'buffering';", "/* MUTANT */")
# i: the wait before playback begins is counted as a stall.
mut('i-startup-stall', "const stalling = this._intent && this._hasPlayed && STALL_STATES.has(state);", "const stalling = this._intent && STALL_STATES.has(state); /* MUTANT */")
# j: a CC button is offered with no caption track.
mut('j-cc-invented', "$.cc.hidden = !tracks.length;", "$.cc.hidden = false; /* MUTANT */")
# k: the hover readout calls an unbuffered point buffered.
mut('k-hover-buffered', "    return 'NOT BUFFERED';", "    return 'BUFFERED'; /* MUTANT */")
# l: a waveform is drawn with no scale to put it on (no duration, or a live stream).
mut('l-wave-no-scale', "this._wave.src === (m.currentSrc || m.src) && sc && !v.isLive;", "this._wave.src === (m.currentSrc || m.src); /* MUTANT */")
# m: an open stall shows a seconds figure that stops counting while the stall goes on.
mut('m-open-stall-seconds', "const closed = this._stallMs / 1000;", "const closed = (this._stallMs + (this._stallFrom === null ? 0 : now - this._stallFrom)) / 1000; /* MUTANT */")
# n: the icon version draws pause over any play asked for, moving or not.
mut('n-pause-icon-pending', "icon($.play, this._intent ? (pending ? 'pending' : 'pause') : 'play');", "icon($.play, this._intent ? 'pause' : 'play'); /* MUTANT */")
# h: a frozen picture under a running clock reads as playing.
mut('h-picture-frozen', "if (this._lastFrame !== null && now - this._lastFrame > freezeMs) return 'picture-frozen';", "/* MUTANT */")
