#!/usr/bin/env python3
"""Generate the ov-authority mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

🔴 GENERATED, NOT HAND-WRITTEN, so a mutant can only ever differ from src by
its one intended change.

Run from tools/authority-test/: python3 mut/make.py
"""
src = open('../../src/ov-authority.js').read()
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. No declared control defaults to AUTO.
mut('a-default-auto',
    "    const control = Object.hasOwn(CONTROL, s.control) ? s.control : null;",
    "    const control = Object.hasOwn(CONTROL, s.control) ? s.control : 'auto';  // MUTANT")

# b: every change counts as announced.
mut('b-unannounced-silent',
    "        const announced = s.announced === true;",
    "        const announced = true;  // MUTANT: a redraw is a notification")

# c: a step behind an inhibited trigger is shown as waiting on it.
mut('c-inhibited-waits',
    "        if (n.trigger && n.inhibited === true) {",
    "        if (false) {  // MUTANT: an inhibited trigger still holds the step")

# d: a selected mode is drawn as armed.
mut('d-selected-as-armed',
    "    const armed = r.armed || (r.selected ? `${r.selected} SELECTED, NOT ARMED` : '—');",
    "    const armed = r.armed || r.selected || '—';  // MUTANT")

# e: an ownerless action is the automation's.
mut('e-ownerless-is-auto',
    "        const owner = Object.hasOwn(OWNER, n.owner) ? n.owner : null;",
    "        const owner = Object.hasOwn(OWNER, n.owner) ? n.owner : 'auto';  // MUTANT")

# f: a system in another mode than the picture is not refused.
mut('f-mixed-mode-silent',
    "      if (s.mode !== undefined && picMode && s.mode !== picMode) {",
    "      if (false) {  // MUTANT: modes mix unseen")

# g: a reversion reads as a plain mode change.
mut('g-reversion-plain',
    "        const reverted = what === 'mode' && s.reversion === true;",
    "        const reverted = false;  // MUTANT")
