#!/usr/bin/env python3
"""Generate src/ov-icons.js from tools/icons.py.

🔴 The register in tools/icons.py is the source. This file is GENERATED, so a
fix applied here has a fuse on it: change the register and re-run.
"""
import json
import os
import sys

from icons import CATEGORY_MEANS, REGISTER, check, symbols


def main():
    bad = check()
    if bad:
        print('🔴 the register fails its own rule:')
        for b in bad:
            print('  ', b)
        return 1

    sprite = []
    meta = {}
    for num, name, cat, means, inner in symbols():
        sid = f'ov-i-{num:02d}'
        sprite.append(f'<symbol id="{sid}" viewBox="0 0 24 24">{inner}</symbol>')
        meta[name] = dict(n=num, cat=cat, means=means)

    js = '''/* GENERATED by tools/gen_icons.py from tools/icons.py. Do not edit.
 *
 * The Overscan symbol register. Every mark has a number and a stated meaning,
 * which is the half of Ron Cobb's Semiotic Standard that transfers: the
 * artwork, names and trademarks are not ours to relicense, and the IDEA is
 * the valuable part anyway.
 *
 * ⭐ The frame is the CATEGORY and the mark is the MEANING, so an unfamiliar
 * symbol is still half-readable: the triangle says hazard before you have
 * worked out what is inside it.
 *
 * 🔴 THERE IS NO GENERIC FALLBACK GLYPH. Asking for a name the register does
 * not define gets a REFUSAL, not a question mark and not a blank: a fallback
 * would be the display inventing a meaning nobody assigned, which is the
 * same failure as a seven-segment readout closing the gap on 1.5.
 */

import { define } from './ov-core.js';
(() => {
  'use strict';

  const REGISTER = %s;

  const SPRITE = '%s';

  let injected = false;
  function inject() {
    if (injected || !document.body) return;
    injected = true;
    const host = document.createElement('div');
    // Hidden, but NOT with `hidden` or `display:none`: a <symbol> referenced
    // from a display:none subtree still resolves, but the wrapper is easier to
    // reason about if it simply has no size and paints nothing.
    host.setAttribute('aria-hidden', 'true');
    host.style.cssText = 'position:absolute;width:0;height:0;overflow:hidden';
    host.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg">' + SPRITE + '</svg>';
    document.body.prepend(host);
  }

  class OvIcon extends HTMLElement {
    static observedAttributes = ['name', 'label'];

    connectedCallback() { inject(); this.render(); }
    attributeChangedCallback() { if (this.isConnected) this.render(); }

    render() {
      const name = (this.getAttribute('name') || '').trim().toLowerCase();
      const entry = REGISTER[name];

      if (!entry) {
        /* 🔴 The refusal. Symbol 00 is reserved for exactly this and is not a
         * symbol in the set: it is the mark that says the set has no mark.
         * The accessible name states the reason and never guesses at what was
         * meant, because a plausible guess is the dangerous kind of wrong. */
        this.innerHTML = svg('ov-i-00');
        this.setAttribute('data-ov-refusal', 'unregistered');
        this.setAttribute('role', 'img');
        this.setAttribute('aria-label',
          `no symbol is registered for "${name || 'nothing'}"`);
        this.removeAttribute('data-ov-means');
        this.removeAttribute('data-ov-n');
        return;
      }

      this.removeAttribute('data-ov-refusal');
      this.innerHTML = svg('ov-i-' + String(entry.n).padStart(2, '0'));
      this.setAttribute('data-ov-n', String(entry.n).padStart(2, '0'));
      this.setAttribute('data-ov-cat', entry.cat || '');
      // ⭐ The meaning travels with the symbol, so "what does this icon mean"
      // is answerable off the element rather than from a table somewhere else.
      this.setAttribute('data-ov-means', entry.means);
      this.setAttribute('role', 'img');
      // The register supplies the name. A caller may override it, because
      // "close this dialog" is a better button label than "isolate" - but it
      // cannot silently have NO name, which is where icon-only controls fail.
      this.setAttribute('aria-label', this.getAttribute('label') || name);
    }
  }

  const svg = (id) =>
    `<svg class="ov-icon__svg" viewBox="0 0 24 24" aria-hidden="true">`
    + `<use href="#${id}"/></svg>`;

  window.OverscanIcons = {
    REGISTER,
    CATEGORIES: %s,
    /* What does this one mean? Answers with a sentence, or null - never with
     * a guess. */
    means(name) {
      const e = REGISTER[String(name || '').toLowerCase()];
      return e ? e.means : null;
    },
  };

  define('ov-icon', OvIcon);
})();
''' % (json.dumps(meta, indent=2, sort_keys=True),
       ''.join(sprite).replace("'", "\\'"),
       json.dumps(CATEGORY_MEANS, indent=2, sort_keys=True))

    os.makedirs('src', exist_ok=True)
    with open('src/ov-icons.js', 'w') as f:
        f.write(js)
    print(f'wrote src/ov-icons.js ({len(meta)} symbols)')

    # 🔴 The spec is GENERATED from the register too, so the document and the
    # drawings cannot drift apart. A published standard whose table disagrees
    # with what ships is worse than no table.
    doc = ["# The Overscan symbol register",
           "",
           "<!-- GENERATED by tools/gen_icons.py from tools/icons.py."
           " Do not edit. -->",
           "",
           "An icon set where every mark has a **number** and a **stated"
           " meaning**, rather than a bag of glyphs.",
           "",
           "The precedent is Ron Cobb's Semiotic Standard, and the precedent"
           " is all that transfers. 🔴 **The artwork, the names and the"
           " trademarks are not ours to relicense** - the vectorisations in"
           " circulation are CC BY 4.0, and upstream is explicit that this"
           " does not extend to Cobb's originals or the film material. The"
           " idea was the valuable half anyway, and these are authored here.",
           "",
           "## The rule",
           "",
           "⭐ **The frame is the category and the mark is the meaning.**",
           "",
           "That is *decoration needs a rule* applied to iconography, and it"
           " buys the set a property almost no icon font has: an unfamiliar"
           " symbol is still half-readable, because the triangle tells you it"
           " is a hazard before you have worked out what is inside it. The"
           " number says the same thing - its tens digit is the category - so"
           " a symbol referred to by number alone is also half-understood.",
           "",
           "Because both the frame and the number carry the category, they can"
           " be **checked against each other**, and they are:"
           " `tools/gen_icons.py` refuses to emit if any symbol has drifted"
           " out of its family.",
           "",
           "## The eight families",
           "",
           "The first five report on a MACHINE: what it is doing (state), what"
           " will hurt you (hazard), which part of it you are looking at"
           " (system), what is moving through it (flow), and what you may do"
           " to it (action).",
           "",
           "The last three are about the SHIP AND THE PEOPLE IN IT, which is"
           " the half of the precedent a console-only set leaves out and the"
           " half that is actually painted on bulkheads: where you are and how"
           " you get out (wayfinding), what is required of the person standing"
           " here (crew), and what the hardware needs from whoever services it"
           " (maintenance).",
           "",
           "🔴 **Two digits ceils the set at nine families of nine.** Eight"
           " families are spent and the ninth tens digit is deliberately left"
           " unspent, because a register that fills its own numbering the"
           " moment it can has no room to be wrong about a category later. A"
           " TENTH family is not a new row in the register, it is a different"
           " numbering scheme, and `check()` refuses rather than letting that"
           " happen quietly.",
           "",
           "## Modifiers",
           "",
           "⭐ **A diagonal slash negates the symbol it crosses**, in any"
           " category. Having exactly one such mark is what keeps it readable:"
           " `14 offline` is a state negated and `44 blocked` is a flow"
           " negated, and neither has to be learned separately once the slash"
           " is.",
           "",
           "⭐ **A horizontal dash inside a frame means absence.**"
           " `15 no reading` is a state with nothing in it; `25 vacuum` is a"
           " space with nothing in it. Not a collision: the frame already said"
           " which kind of absence.",
           "",
           "## Sub-rules, which are not modifiers",
           "",
           "A modifier means one thing everywhere. These two mean something"
           " only INSIDE their family, so they are written down separately"
           " rather than smuggled in as a third and fourth modifier.",
           "",
           "⭐ **In the state circle, how much of the dot is filled is how much"
           " of the thing is working.** Filled is `11 nominal`, half is"
           " `17 degraded`, hollow is `16 standby`. Three symbols, one"
           " gradient, nothing to memorise.",
           "",
           "⭐ **In the flow channel, the line and the chevrons carry the"
           " rate.** A dashed line is `49 trickle`, a single chevron is the"
           " ordinary case, and a doubled chevron is `48 surge`. Rate is"
           " drawn, not labelled.",
           "",
           "## Construction",
           "",
           "24x24 grid, stroke 2, butt caps, miter joins, `currentColor`"
           " throughout so a symbol takes the theme like everything else."
           " Nothing is filled except where filling is the distinction"
           " (`11 nominal` against `15 no reading`).",
           "",
           "⚠️ **A frame that tapers has a wedge for an interior, not a"
           " box.** Two passes at the hazard marks failed on this: the first"
           " drew them too small to read at 30px, and the second drew"
           " four-stroke marks sized for a box, which came out as a bowtie, a"
           " bolt crossing its own frame, and spokes leaving the bottom edge."
           " Hazard marks are two or three bold strokes, sat low where the"
           " wedge is wide. The shield has the same problem upside down, so"
           " crew marks stay clear of its tip.",
           "",
           "⚠️ **A mark can read as a letter, or as a bowtie.** `39 structure`"
           " was an X between two rails, which collapses to an hourglass, and"
           " `37 navigation` was a notched arrowhead, which is a capital A no"
           " matter how deep the notch is cut. The fixes generalise: a beam"
           " section cannot collapse, and a SOLID shape cannot be a"
           " letterform, because letterforms are strokes.",
           "",
           "## A mark never crowds its frame",
           "",
           "⭐ The frame carries the category, so it has to survive being"
           " looked at quickly, and a mark run up against the frame edge fuses"
           " with it. `tools/clearance.py` measures the visible gap on every"
           " symbol - flattening frame and mark to point clouds, taking the"
           " closest approach, and subtracting the stroke each actually paints"
           " - and refuses if any symbol is tight.",
           "",
           "⭐ **The margin is one ninth of the room the frame has.** One"
           " absolute number is the obvious rule and it is wrong, because the"
           " frames are not the same size inside: the state circle holds an"
           " inscribed disc of 9.00 and the hazard triangle holds 5.40, so a"
           " figure generous enough for the circle shrinks hazard marks back"
           " to the size that already failed a pass. Every frame gives up the"
           " same PROPORTION of its interior instead, with the roomiest frame"
           " setting the constant at 1.00.",
           "",
           "## There is no fallback glyph",
           "",
           "🔴 Asking for a name the register does not define gets a"
           " **refusal**, not a question mark and not a nearest match. A"
           " fallback would be the display inventing a meaning nobody"
           " assigned, which is the same failure as a seven-segment readout"
           " closing the gap on `1.5`. Symbol **00** is reserved for saying"
           " the register has no answer and is not a symbol in the set.",
           "",
           "`OverscanIcons.means(name)` answers with the sentence below, or"
           " `null`. Never with a guess.",
           "",
           "## The register",
           ""]
    for cat, cmeans in CATEGORY_MEANS.items():
        doc += [f"### {cat} &mdash; {cmeans}", "",
                "| | name | means |", "|---:|---|---|"]
        for num, name, c, means, _m in REGISTER:
            if c == cat:
                doc.append(f"| **{num:02d}** | `{name}` | {means} |")
        doc.append("")
    doc += ["### reserved", "", "| | name | means |", "|---:|---|---|"]
    for num, name, c, means, _m in REGISTER:
        if c is None:
            doc.append(f"| **{num:02d}** | `{name}` | {means} |")
    doc.append("")
    with open('ICONS.md', 'w') as f:
        f.write('\n'.join(doc))
    print(f'wrote ICONS.md')
    return 0


if __name__ == '__main__':
    sys.exit(main())
