#!/usr/bin/env python3
"""Generate the Svelte, Vue and React wrappers from custom-elements.json.

⭐ WHY THERE IS ANYTHING TO GENERATE AT ALL. Custom elements are
framework-agnostic and most of this kit needs no wrapper: the CSS layer is
class names on plain markup, and an element with no data and no events works
bare in all three. Two things do not survive contact with a framework:

1. 🔴 EVENTS. Every event here is namespaced with a colon (`ov:commit`), and a
   colon has no declarative spelling in two of the three. Svelte 5 replaced the
   `on:` directive with plain properties, so `onov:commit` is not an
   identifier; React 19 binds custom events as `on<Event>`, and `onov:commit`
   is not writable in JSX. Vue can bind it. The namespace stays: it is what
   keeps `ov:change` from colliding with a host app's own `change`, and one
   addEventListener is a cheap price. THE COLON IS WHY WRAPPERS EXIST.

2. 🔴 DATA. An attribute is a string, so an array and a null cannot travel
   through one: `values="1,2,3"` round-trips through text and `null` arrives as
   the word "null". Every reading is set as a PROPERTY, never an attribute, or
   the refusal protocol is lost at the door.

Everything else passes straight through as attributes.

⚠️ The wrappers do NOT re-implement the protocol, validate, coerce or default.
A wrapper that turned `null` into `0`, or dropped it from an array, would be
the seven-segment failure one layer up. They move values and events, nothing
more.
"""
import json
import pathlib
import re
import sys

OUT = pathlib.Path('src')


# ⚠️ The spellings are NOT computed here. tools/api.py puts them in the
# manifest and this reads them, so the reference pages, the wrappers and the
# types cannot disagree about what an event is called in each framework.


def load():
    m = json.loads(pathlib.Path('custom-elements.json').read_text())
    els = [d for mod in m['modules'] for d in mod['declarations']]
    return sorted(els, key=lambda e: e['name'])


def iface(e):
    return e['wrappers']['component']


REACT_RUNTIME = '''/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import { createElement, forwardRef, useEffect, useLayoutEffect, useRef } from 'react';

/* useLayoutEffect warns during SSR, where there is no layout to read. */
const useIso = typeof document === 'undefined' ? useEffect : useLayoutEffect;

/* 🔴 THE WRAPPER SETS ATTRIBUTES ITSELF, AND THIS IS THE WHOLE REASON IT IS
 * NOT A ONE-LINER.
 *
 * All three frameworks apply the same heuristic to a custom element: if the
 * prop NAME EXISTS ON THE ELEMENT, set it as a property, otherwise set an
 * attribute. This kit has 47 GETTER-ONLY properties across 21 elements, and
 * many of them share a name with a real attribute: digits, step, lat, lon,
 * range, span, period, rings, hold, sweeps, floor, traces, at, duration, mode.
 *
 * So `<OvSegment digits="4" />` made React find `digits` on the element, try to
 * assign it, and throw "Cannot set property digits of #<OvSegment> which has
 * only a getter". That did not degrade: it took down the ENTIRE React tree, and
 * the same heuristic exists in Vue and in Svelte's custom-element path.
 *
 * Passing attributes through the framework is therefore not an option, and
 * neither is a list of which names are safe, since that list would rot against
 * src/. The wrapper hands the framework nothing but a ref and applies every
 * attribute itself, which is deterministic and identical on React 18 and 19.
 */
function applyAttrs(el, next, prev) {
  for (const key of Object.keys(prev)) {
    if (!(key in next)) el.removeAttribute(key === 'className' ? 'class' : key);
  }
  for (const [key, value] of Object.entries(next)) {
    const name = key === 'className' ? 'class' : key;
    if (name === 'style' && value && typeof value === 'object') {
      Object.assign(el.style, value);
      continue;
    }
    if (value === null || value === undefined || value === false) el.removeAttribute(name);
    else if (value === true) el.setAttribute(name, '');
    else el.setAttribute(name, String(value));
  }
}


/* Build one React component around one custom element.
 *
 * ⚠️ Properties are set through a ref rather than passed as JSX attributes,
 * and not because React 19 cannot do it. React 19 WILL set a property when the
 * name exists on the element, but that check happens when React renders, and
 * whether the element has upgraded by then depends on module and network
 * order. When it has not, the value silently becomes an ATTRIBUTE instead:
 * an array stringifies to "1,2,3" and a null becomes the word "null", which
 * the reading protocol reads as a value rather than a dropout. Setting through
 * the ref is order-independent and behaves the same on React 18.
 */
export function wrap(tag, propNames, events) {
  const Component = forwardRef(function OverscanElement(props, forwarded) {
    const host = useRef(null);
    const { children, ...rest } = props;

    const values = {};
    const handlers = {};
    const attrs = {};
    for (const [key, value] of Object.entries(rest)) {
      if (propNames.includes(key)) values[key] = value;
      else if (key in events) handlers[key] = value;
      else attrs[key] = value;
    }

    /* Latest handlers without re-binding listeners on every render. */
    const latest = useRef(handlers);
    latest.current = handlers;

    const lastAttrs = useRef({});

    useIso(() => {
      const el = host.current;
      if (!el) return;
      applyAttrs(el, attrs, lastAttrs.current);
      lastAttrs.current = attrs;
      for (const [key, value] of Object.entries(values)) {
        /* undefined means "not driving this property", which is NOT the same
         * as null. Writing undefined would clear a value the markup set. */
        if (value !== undefined && el[key] !== value) el[key] = value;
      }
    });

    useEffect(() => {
      const el = host.current;
      if (!el) return undefined;
      const off = Object.entries(events).map(([key, type]) => {
        const handler = (event) => {
          const fn = latest.current[key];
          if (typeof fn === 'function') fn(event);
        };
        el.addEventListener(type, handler);
        return () => el.removeEventListener(type, handler);
      });
      return () => off.forEach((f) => f());
    }, []);

    /* Only a ref. Nothing else is handed to React: see applyAttrs. */
    return createElement(tag, {
      ref: (node) => {
        host.current = node;
        if (typeof forwarded === 'function') forwarded(node);
        else if (forwarded) forwarded.current = node;
      },
    }, children);
  });
  Component.displayName = tag;
  return Component;
}
'''

VUE_RUNTIME = '''/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */
import { defineComponent, h, onBeforeUnmount, onMounted, ref, watchEffect } from 'vue';

/* 🔴 THE WRAPPER SETS ATTRIBUTES ITSELF, AND THIS IS THE WHOLE REASON IT IS
 * NOT A ONE-LINER.
 *
 * All three frameworks apply the same heuristic to a custom element: if the
 * prop NAME EXISTS ON THE ELEMENT, set it as a property, otherwise set an
 * attribute. This kit has 47 GETTER-ONLY properties across 21 elements, and
 * many of them share a name with a real attribute: digits, step, lat, lon,
 * range, span, period, rings, hold, sweeps, floor, traces, at, duration, mode.
 *
 * So `<OvSegment digits="4" />` made React find `digits` on the element, try to
 * assign it, and throw "Cannot set property digits of #<OvSegment> which has
 * only a getter". That did not degrade: it took down the ENTIRE React tree, and
 * the same heuristic exists in Vue and in Svelte's custom-element path.
 *
 * Passing attributes through the framework is therefore not an option, and
 * neither is a list of which names are safe, since that list would rot against
 * src/. The wrapper hands the framework nothing but a ref and applies every
 * attribute itself, which is deterministic and identical on React 18 and 19.
 */
function applyAttrs(el, next, prev) {
  for (const key of Object.keys(prev)) {
    if (!(key in next)) el.removeAttribute(key === 'className' ? 'class' : key);
  }
  for (const [key, value] of Object.entries(next)) {
    const name = key === 'className' ? 'class' : key;
    if (name === 'style' && value && typeof value === 'object') {
      Object.assign(el.style, value);
      continue;
    }
    if (value === null || value === undefined || value === false) el.removeAttribute(name);
    else if (value === true) el.setAttribute(name, '');
    else el.setAttribute(name, String(value));
  }
}


/* Vue is the only one of the three that CAN bind `ov:commit` in a template,
 * as `@ov:commit`. The wrapper still exists so the three spellings match, so
 * readings are set as properties rather than attributes, and so the event
 * arrives under a name that looks like every other Vue event.
 */
export function wrap(tag, propNames, events) {
  return defineComponent({
    name: tag,
    /* undefined default, deliberately: it means "not driving this property",
     * which the reading protocol distinguishes from null, a dropout. */
    props: Object.fromEntries(propNames.map((n) => [n, { default: undefined }])),
    emits: Object.keys(events),
    setup(props, { attrs, slots, emit }) {
      const host = ref(null);

      let lastAttrs = {};
      watchEffect(() => {
        const el = host.value;
        if (!el) return;
        applyAttrs(el, attrs, lastAttrs);
        lastAttrs = { ...attrs };
        for (const name of propNames) {
          if (props[name] !== undefined && el[name] !== props[name]) {
            el[name] = props[name];
          }
        }
      });

      let off = [];
      onMounted(() => {
        const el = host.value;
        if (!el) return;
        off = Object.entries(events).map(([name, type]) => {
          const handler = (event) => emit(name, event);
          el.addEventListener(type, handler);
          return () => el.removeEventListener(type, handler);
        });
      });
      onBeforeUnmount(() => { off.forEach((f) => f()); off = []; });

      /* ref only; every attribute is applied by applyAttrs above. */
      return () => h(tag, { ref: host },
        slots.default ? slots.default() : undefined);
    },
  });
}
'''

SVELTE_COMPONENT = '''<!-- GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. -->
<script>
  /* {tag}
   *
   * Svelte 5 replaced the `on:` directive with plain properties, so a
   * colon-namespaced event has NO declarative spelling: `onov:{first}` is not
   * an identifier. Events arrive as callback props and are attached here.
   */
  import '../{module}';

  let {{ {props}children, ...rest }} = $props();

  let host = $state(null);

  /* 🔴 `rest` is applied with setAttribute rather than spread onto the element.
   * Svelte's custom-element path sets a prop as a PROPERTY when the name
   * exists on the element, and this kit has 47 getter-only properties whose
   * names collide with real attributes (digits, step, lat, range, duration).
   * Assigning one throws. See the React runtime for the full account. */
  $effect(() => {{
    if (!host) return;
    for (const [key, value] of Object.entries(rest)) {{
      const name = key === 'className' ? 'class' : key;
      if (value === null || value === undefined || value === false) host.removeAttribute(name);
      else if (value === true) host.setAttribute(name, '');
      else host.setAttribute(name, String(value));
    }}
  }});

  $effect(() => {{
{assigns}  }});

  $effect(() => {{
    if (!host) return;
    const off = [
{listeners}    ];
    return () => off.forEach((f) => f());
  }});
</script>

<svelte:element this={{'{tag}'}} bind:this={{host}}>{{@render children?.()}}</svelte:element>
'''


GENERATED = "/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */"


def emit_split(els, framework, runtime):
    """One module per component, and an index that only re-exports them.

    🔴 THE INDEX USED TO IMPORT THE WHOLE KIT. `import '../overscan.js'` sat at
    the top of index.js, so `import { OvRadar } from 'overscan/react'`
    registered every element in the kit, and in a Vite production build one
    component cost 143 kB gzip over React alone (tools/consumer-test.sh,
    2026-09-12). Each component now imports only its own element, the way the
    Svelte components always did, and package.json lists the files that DO have
    side effects, so a bundler drops every wrapper module nobody imports along
    with the element it would have loaded.

    ⚠️ DEV SERVERS DO NOT TREE-SHAKE. Vite dev pre-bundles the whole index, so
    every element still registers there. The cost is a production-build
    property, and the consumer check asserts it only in the build.
    """
    d = OUT / framework
    d.mkdir(exist_ok=True)
    (d / 'runtime.js').write_text(runtime)
    index, keep = [GENERATED], {'index.js', 'runtime.js'}
    for e in els:
        props = [m['name'] for m in e['members']]
        evs = '{' + ', '.join(f"{k}: '{v}'"
                                 for k, v in e['wrappers'][framework].items()) + '}'
        file = f'{iface(e)}.js'
        keep.add(file)
        (d / file).write_text('\n'.join([
            GENERATED,
            f"import '../{e['module'].replace('src/', '', 1)}';",
            "import { wrap } from './runtime.js';",
            '',
            f"export const {iface(e)} = wrap('{e['name']}', {json.dumps(props)}, {evs});",
        ]) + '\n')
        index.append(f"export {{ {iface(e)} }} from './{file}';")
    # A removed element must not leave a wrapper behind that imports nothing.
    for stale in sorted(p for p in d.glob('*.js') if p.name not in keep):
        stale.unlink()
    (d / 'index.js').write_text('\n'.join(index) + '\n')
    return len(els)


def emit_react(els):
    return emit_split(els, 'react', REACT_RUNTIME)


def emit_vue(els):
    return emit_split(els, 'vue', VUE_RUNTIME)


def emit_svelte(els):
    d = OUT / 'svelte'
    d.mkdir(exist_ok=True)
    for e in els:
        props = [m['name'] for m in e['members']]
        handlers = list(e['wrappers']['svelte'])
        decl = ''.join(f'{n} = undefined, ' for n in props + handlers)
        assigns = ''.join(
            f"    if (host && {n} !== undefined) host.{n} = {n};\n" for n in props)
        if not assigns:
            assigns = "    void host;\n"
        listeners = ''.join(
            f"      (() => {{ const h = (e) => {name}?.(e); "
            f"host.addEventListener('{ev}', h); "
            f"return () => host.removeEventListener('{ev}', h); }})(),\n"
            for name, ev in e['wrappers']['svelte'].items())
        (d / f"{iface(e)}.svelte").write_text(SVELTE_COMPONENT.format(
            tag=e['name'], module=e['module'].replace('src/', ''),
            first=(e['events'][0].split(':', 1)[1] if e['events'] else 'commit'),
            props=decl, assigns=assigns, listeners=listeners))
    index = ["/* GENERATED by tools/gen_wrappers.py. Do not edit; re-run the script. */"]
    for e in els:
        index.append(f"export {{ default as {iface(e)} }} "
                     f"from './{iface(e)}.svelte';")
    (d / 'index.js').write_text('\n'.join(index) + '\n')
    return len(els)


def selftest():
    """Refuses to report until it has seen the cases that matter."""
    fails = []
    els = load()
    tr = next((e for e in els if e['name'] == 'ov-transport'), None)
    if tr:
        w = tr['wrappers']
        if w['react'].get('onPlay') != 'ov:play':
            fails.append(f"react spelling wrong: {w['react']}")
        if w['vue'].get('play') != 'ov:play':
            fails.append(f"vue spelling wrong: {w['vue']}")
        if w['svelte'].get('onplay') != 'ov:play':
            fails.append(f"svelte spelling wrong: {w['svelte']}")

    # 40 since ov-countdown (2026-09-11).
    # 43 since ov-track (2026-09-11).
    # 48 since ov-downlink (2026-09-11).
    # 53 since ov-orbit (2026-09-11).
    # 81 since ov-geomap and ov-tactical.
    # 82 since ov-watchdog.
    # 83 since ov-authority.
    # 84 since ov-solid.
    # 85 since ov-datablock.
    if len(els) != 85:
        fails.append(f'expected 85 elements, manifest has {len(els)}')

    # 🔴 The reason wrappers exist. If an element with events came back with
    # none, the wrapper would be a silent pass-through and the colon problem
    # would be unsolved on that element.
    tr = next((e for e in els if e['name'] == 'ov-transport'), None)
    if not tr or 'ov:play' not in tr['events'] or 'ov:seek' not in tr['events']:
        fails.append('ov-transport lost its events; the wrapper would bind nothing')

    ch = next((e for e in els if e['name'] == 'ov-chart'), None)
    if not ch or [m['name'] for m in ch['members']] != ['values']:
        fails.append('ov-chart lost its values property; readings would go '
                     'through attributes and stringify')
    return fails


if __name__ == '__main__':
    f = selftest()
    if f:
        print('gen_wrappers.py SELFTEST FAILED:', *f, sep='\n  ')
        sys.exit(1)
    print('selftest ok')
    els = load()
    print(f'wrote src/react/  ({emit_react(els)} components)')
    print(f'wrote src/vue/    ({emit_vue(els)} components)')
    print(f'wrote src/svelte/ ({emit_svelte(els)} components)')
