#!/usr/bin/env python3
"""Generate the two single entries a consumer imports: overscan.css and overscan.js.

🔴 WHY THIS IS A GENERATOR AND NOT A FILE SOMEBODY EDITS. The entry was
hand-maintained, and the failure mode is silent: add a stylesheet to src/,
forget the @import, and the kit still works in the repo, because every demo
page links the files it needs directly. It breaks only for someone who
installed the package, and it breaks as a MISSING RULE rather than an error, so
the component just looks wrong. Nobody here would ever see it.

⚠️ THE ORDER IS THE CASCADE. It is the order the demo pages have always linked
these files in, so the kit resolves against itself exactly as it does here.
This list is not an inventory and sorting it would be a visual change.

🔴 A NEW FILE MUST BE PLACED DELIBERATELY. An unlisted stylesheet is REFUSED
and named rather than appended, because appending is a guess about the cascade
and the guess is invisible until two rules disagree.
"""
import pathlib
import re
import sys

ORDER = [
    'tokens', 'finish', 'chrome', 'field', 'motion', 'flip', 'layout', 'control',
    'chart', 'gauge', 'radar', 'track', 'reticle', 'plate', 'wireframe', 'schematic', 'locator', 'horizon', 'match', 'polygon', 'sequence', 'histogram', 'fan', 'donut', 'baseline', 'verifier', 'topology', 'continuity', 'timestack', 'coverage', 'likelihood', 'consistency', 'endurance', 'ladder', 'dose', 'rangebar', 'allocator', 'downlink', 'orbit', 'annunciator', 'procedure', 'countdown', 'timeline', 'segment', 'flap', 'scope',
    # The list-4 instruments, placed together at the end of the instrument run
    # rather than beside their nearest kin: none of them is meant to override or
    # be overridden by another component, so the only deliberate answer is a
    # position where nothing above or below has a rule that could reach them.
    'quorum', 'station', 'mosaic', 'balance', 'position', 'clearance', 'score', 'switch', 'avatar', 'vitals', 'ecg', 'geomap', 'tactical',
    'ascii', 'graph', 'grid', 'term', 'icon', 'log', 'table', 'aux', 'cli',
    'form', 'bevel', 'surface', 'ornament', 'window', 'fault', 'text',
    'code',
]

# 🔴 OPT-IN STYLESHEETS: in src/ and in the package, but not in overscan.css.
# ov-player's two sheets are 9.4 kB gzip of transport chrome and drawn icons
# that a page without a player should not pay for (decided 2026-09-13). A page
# with a player links them after overscan.css. Their rules reach nothing
# outside the player, so loading them after the entry instead of at their old
# place in the cascade changes nothing on screen.
CSS_OPT_IN = ['player', 'player-icons']
# Which element needs which opt-in sheet, so a generated page that shows the
# element and links only overscan.css can add them, and so the import examples
# shown for that element name them.
CSS_OPT_IN_FOR = {'ov-player': ['player', 'player-icons']}

HEAD = """/* GENERATED by tools/gen_entry.py. Do not edit; re-run the script.
 *
 * Overscan, whole kit, one file:  import 'overscan/overscan.css'
 *
 * Except the media player: a page with <ov-player> also imports
 * 'overscan/src/player.css' and 'overscan/src/player-icons.css'.
 *
 * ⚠️ THE ORDER HERE IS THE CASCADE and it is not alphabetical. It is the order
 * the demo pages have always linked these files in, so the kit resolves against
 * itself exactly as it does in the repo. Reordering is a visual change.
 *
 * Every file wraps itself in `@layer overscan`, so importing them here does not
 * decide their layer and the single-file and per-file paths behave identically.
 * Unlayered author CSS beats all of it, which is the point of the layer.
 */

"""


JS_HEAD = """/* GENERATED by tools/gen_entry.py. Do not edit; re-run the script.
 *
 * Overscan, whole kit, one module:  import 'overscan'
 *
 * 🔴 EVERY IMPORT HERE IS A SIDE EFFECT AND NONE OF THEM IS DEAD CODE. Each
 * module registers its custom element on load, so a bundler told these files
 * are side-effect-free would tree-shake the entire kit and leave a page of
 * unupgraded tags with no error anywhere. package.json lists src/ov-*.js,
 * this file and the CSS under sideEffects for exactly this reason; only the
 * React/Vue wrappers and the shader modules sit outside it, so the ones nobody
 * imports can be dropped. Do not "optimise" the list.
 *
 * Importing a single element instead is supported and smaller:
 *     import 'overscan/src/ov-chart.js'
 * CSS is separate either way: import 'overscan/overscan.css'.
 */

"""

# Load order for the JS entry. The base modules come first so anything reading
# window.Overscan at import time finds it; after that it is alphabetical,
# because a module imports what it needs and does not rely on this order.
JS_FIRST = ['ov-core', 'ov-source', 'ov-refusal', 'ov-gl']

# 🔴 DATA, NOT A MODULE THE KIT RUNS. ov-countries.js is 20 kB of outlines that
# only a page drawing a world wants, so it stays out of `import 'overscan'` and
# is imported by name (overscan/countries). It registers nothing, so leaving it
# out cannot leave a tag unupgraded, which is the hole build_js() closes.
JS_OPT_IN = ['ov-countries']


def build_js():
    """🔴 THE SAME SILENT HOLE THE CSS ENTRY HAD, closed the same way.

    Add a module to src/, forget the import, and nothing breaks HERE, because
    every demo page loads what it needs directly. It breaks only for someone
    who installed the package, and it breaks as a MISSING ELEMENT rather than
    an error: the tag stays unupgraded and simply renders nothing.

    Found by the Flip session, whose src/ov-flip.js was the one unlisted module
    at the time. Nobody would have noticed until an install.
    """
    have = sorted(p.stem for p in pathlib.Path('src').glob('ov-*.js'))
    rest = [n for n in have if n not in JS_FIRST and n not in JS_OPT_IN]
    missing = [n for n in JS_FIRST + JS_OPT_IN if n not in have]
    if missing:
        raise SystemExit(f'gen_entry: REFUSED, listed modules absent: {missing}')
    registers = [n for n in JS_OPT_IN if re.search(r'\bdefine\(', pathlib.Path(f'src/{n}.js').read_text())]
    if registers:
        raise SystemExit(f'gen_entry: REFUSED, opt-in modules must register nothing, and these define an element: {registers}')
    order = JS_FIRST + rest
    body = '\n'.join(f"import './{n}.js';" for n in order)
    return (JS_HEAD + body
            + "\n\nexport { Overscan, define } from './ov-core.js';\n"
              "export { default as OverscanRefusal } from './ov-refusal.js';\n")


def build():
    have = {p.stem for p in pathlib.Path('src').glob('*.css')} - {'overscan'}
    if set(ORDER) & set(CSS_OPT_IN):
        raise SystemExit('gen_entry: REFUSED: a stylesheet is both in ORDER and opt-in: '
                         + ', '.join(sorted(set(ORDER) & set(CSS_OPT_IN))))
    missing = have - set(ORDER) - set(CSS_OPT_IN)
    stale = (set(ORDER) | set(CSS_OPT_IN)) - have
    if missing or stale:
        parts = []
        if missing:
            parts.append(
                'REFUSED: these stylesheets exist in src/ but are not placed in '
                'ORDER, so they would be missing from the package entry: '
                + ', '.join(sorted(missing))
                + '. Put each one where it belongs in the cascade; do not append '
                  'it, because appending is a guess that stays invisible until '
                  'two rules disagree.')
        if stale:
            parts.append('REFUSED: ORDER names stylesheets that no longer exist: '
                         + ', '.join(sorted(stale)))
        raise SystemExit('gen_entry: ' + '\n           '.join(parts))
    return HEAD + '\n'.join(f"@import url('{n}.css');" for n in ORDER) + '\n'


def bad_escapes():
    """🔴 A DOUBLED BACKSLASH IN `content:` IS A LITERAL BACKSLASH, NOT A GLYPH.

    `content: " \\\\2191"` renders the six characters `\\2191` on screen where an
    arrow was meant. It is invisible in the source, since a CSS escape already
    starts with a backslash and two look like an ordinary escaping habit, and it
    is invisible in review because the string still "looks like" a code point.
    `ov-table` shipped it on both sort arrows and the header read "STATE \\2191"
    on every sorted column.

    ⚠️ Narrow on purpose: only inside `content:`, and only when four hex digits
    follow, which is a code point somebody meant to write. A doubled backslash
    anywhere else can be a genuine literal.
    """
    fails = []
    for css in sorted(pathlib.Path('src').glob('*.css')):
        for n, line in enumerate(css.read_text().splitlines(), 1):
            if 'content:' in line and re.search(r'\\\\\\\\[0-9a-fA-F]{4}', line):
                fails.append(f'{css.name}:{n} has a doubled backslash in content:, '
                             f'which renders as text rather than a glyph')
    return fails


def selftest():
    fails = []
    fails += bad_escapes()
    # and the check has to be able to fail
    if not re.search(r'\\\\\\\\[0-9a-fA-F]{4}', r'content: " \\\\2191"'):
        fails.append('the doubled-backslash check cannot recognise its own case')
    real = {p.stem for p in pathlib.Path('src').glob('*.css')} - {'overscan'}
    if set(ORDER) | set(CSS_OPT_IN) != real:
        fails.append(f'ORDER and CSS_OPT_IN disagree with src/: {(set(ORDER) | set(CSS_OPT_IN)) ^ real}')
    if sorted({n for sheets in CSS_OPT_IN_FOR.values() for n in sheets}) != sorted(CSS_OPT_IN):
        fails.append('CSS_OPT_IN_FOR does not cover exactly the opt-in stylesheets')
    if any(f"'{n}.css'" in build() for n in CSS_OPT_IN):
        fails.append('an opt-in stylesheet is imported by overscan.css')
    # 🔴 Prove the refusal fires, or it is decoration.
    saved = list(ORDER)
    try:
        ORDER.remove('code')
        try:
            build()
            fails.append('an unplaced stylesheet was not refused')
        except SystemExit:
            pass
    finally:
        ORDER[:] = saved
    # The JS entry must list EVERY module but the opt-in data, or an installed
    # consumer silently loses an element. Assert it against src/ rather than trusting it.
    js = build_js()
    mods = {p.stem for p in pathlib.Path('src').glob('ov-*.js')} - set(JS_OPT_IN)
    listed = set(re.findall(r"import '\./(ov-[\w-]+)\.js'", js))
    if listed != mods:
        fails.append(f'JS entry and src/ disagree: {sorted(mods ^ listed)}')
    # And an opt-in module that registered an element would be a tag nobody's
    # page upgrades: prove that is refused, not just stated.
    JS_OPT_IN.append('ov-core')
    try:
        build_js()
        fails.append('an opt-in module that defines an element was not refused')
    except SystemExit:
        pass
    finally:
        JS_OPT_IN.remove('ov-core')
    return fails


if __name__ == '__main__':
    f = selftest()
    if f:
        print('gen_entry.py SELFTEST FAILED:', *f, sep='\n  ')
        sys.exit(1)
    print('selftest ok')
    css = pathlib.Path('src/overscan.css')
    css.write_text(build())
    print(f'wrote {css} ({len(ORDER)} imports)')
    js = pathlib.Path('src/overscan.js')
    js.write_text(build_js())
    n = build_js().count('import ./') or build_js().count("import './")
    print(f'wrote {js} ({n} modules)')
