#!/usr/bin/env python3
"""Generate src/shaders/<name>.js and src/shaders/index.js from the .glsl files.

    python3 tools/gen_shaders.py

🔴 WHY SHADERS ARE MODULES AND NOT FETCHES. ov-gl.js used to fetch
`shaders/<name>.glsl` relative to its own URL, built at runtime. A browser
with no build step follows that. A BUNDLER DOES NOT: Vite only copies an asset
it can see in a literal `new URL('./x', import.meta.url)`, so in a bundled app
every shader 404'd (build: /assets/shaders/field.glsl, dev:
/node_modules/overscan/shaders/field.glsl), the element set
data-ov-shader="missing", and nothing reached the console. Measured
2026-09-12 against the packed tarball.

A literal `import('./field.js')` is the one spelling a browser, a CDN and every
bundler all resolve, so each shader becomes a module exporting its source, and
index.js is a table of those imports.

⚠️ LAZY, ON PURPOSE. The table holds functions, not imports: an element loads
only the shader it names, when it names it. Static imports would put all ten
(about 20 kB gzip) in front of every GL element.

⚠️ ALL TEN ARE IN THE TABLE because ov-field reads its shader name from an
attribute or the theme's --ov-fx-shader at runtime, so no static analysis can
know which ones a page will want.

The .glsl files stay the source anyone edits: demo/glcheck.html and the design
files read them directly. Never edit the generated .js.

Prove it fails: hand-edit src/shaders/field.js and run release.py; the regen
fixpoint names the file.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHADERS = ROOT / 'src' / 'shaders'
HEADER = '/* GENERATED by tools/gen_shaders.py from {src}. Do not edit; edit the .glsl and re-run. */\n'
NAME_RE = re.compile(r'^[a-z][a-z0-9-]*$')


def main():
    glsl = sorted(SHADERS.glob('*.glsl'))
    if not glsl:
        sys.exit('gen_shaders: REFUSED, no .glsl files in src/shaders')
    bad = [p.name for p in glsl if not NAME_RE.match(p.stem)]
    if bad:
        # The name is both an object key and a file name in index.js.
        sys.exit(f'gen_shaders: REFUSED, shader names must be lowercase words: {bad}')

    for p in glsl:
        # json.dumps escapes quotes, backslashes and newlines, and a JSON string
        # is a valid JS string literal, so no GLSL can break out of it.
        body = HEADER.format(src=p.name) + f'export default {json.dumps(p.read_text())};\n'
        (SHADERS / f'{p.stem}.js').write_text(body)

    table = '\n'.join(f"  '{p.stem}': () => import('./{p.stem}.js')," for p in glsl)
    (SHADERS / 'index.js').write_text(
        HEADER.format(src='every .glsl here')
        + '/* Shader name -> loader. Literal imports so bundlers can see every file;\n'
        + ' * functions so nothing loads until an element names it. */\n'
        + f'export const SHADERS = {{\n{table}\n}};\n')

    stale = sorted(p.name for p in SHADERS.glob('*.js')
                   if p.name != 'index.js' and not (SHADERS / f'{p.stem}.glsl').exists())
    for name in stale:
        (SHADERS / name).unlink()

    print(f'wrote src/shaders/  ({len(glsl)} shaders + index.js'
          + (f', removed stale {stale}' if stale else '') + ')')


if __name__ == '__main__':
    main()
