#!/usr/bin/env python3
"""Generate the ov-switch mutants: one copy per refusal, each broken on purpose.
The gate MUST go red against every one.

Run from tools/switch-test/: python3 mut/make.py
"""
src = open('../../src/ov-switch.js').read()
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)
head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. The command writes the talkback, so the flag shows the
# position that was set as though a sensor had reported it.
mut('a-talkback-follows-set',
    "    this._commandedAt = Date.now();\n",
    "    this._commandedAt = Date.now();\n    this._talkback = to;  // MUTANT: set is confirmed\n")

# b: no barberpole. Between positions the flag falls back to the handle.
mut('b-no-barberpole',
    "const shown = typeof tb === 'string' && pos.includes(tb) ? tb : null;",
    "const shown = typeof tb === 'string' && pos.includes(tb) ? tb : r.set;  // MUTANT")

# c: a command never runs out, so no talkback is in transit forever.
mut('c-transit-never-expires',
    "const inWindow = this._commandedAt !== null && Date.now() - this._commandedAt < this.transitMs();",
    "const inWindow = this._commandedAt !== null;  // MUTANT: no overrun")

# d: any reported position counts as agreement with the handle.
mut('d-disagree-passes',
    "const agrees = tb === r.set;",
    "const agrees = typeof tb === 'string';  // MUTANT: a position is a position")

# e: the guard is drawn and does nothing: one action commands.
mut('e-guard-ignored',
    "    if (this.guarded() && !this._armed) return false;",
    "    if (false) return false;  // MUTANT: the guard is decoration")

# f: armed, and not shown.
mut('f-armed-hidden',
    "    setAttr(this, 'data-ov-armed', this._armed ? '' : null);",
    "    setAttr(this, 'data-ov-armed', null);  // MUTANT: armed looks safe")

# g: a flick switch latches, so its handle shows the command as a state.
mut('g-flick-latches',
    "    r.handle = this.kind() === 'flick' ? this.rest() : r.set;",
    "    r.handle = r.set;  // MUTANT: it stays where it was flicked")

# h: SAFE does not remove the armed condition.
mut('h-safe-keeps-armed',
    "  safe() { this._armed = false;",
    "  safe() { this._armed = this._armed;  // MUTANT")

# i: the lamp lights on the rocker, not on the talkback.
mut('i-lamp-follows-set',
    "setAttr(this, 'data-ov-lit', r.state === 'agree' && lamp !== null && r.set === lamp ? '' : null);",
    "setAttr(this, 'data-ov-lit', lamp !== null && r.set === lamp ? '' : null);  // MUTANT")

# j: a reading's command age is dropped, so a command still in transit reads
# as though nobody had commanded anything.
mut('j-reading-drops-age',
    "this._commandedAt = r.commandedAgo !== undefined && r.commandedAgo !== null && Number.isFinite(ago) && ago >= 0 ? Date.now() - ago * 1000 : null;",
    "this._commandedAt = null;  // MUTANT: the age is ignored")
