#!/usr/bin/env python3
"""Generate the ov-quorum mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

🔴 GENERATED, NOT HAND-WRITTEN, and that is the point. The first set of these
was written by hand and then the element was polished three times underneath
them, so by the time they were read again each mutant differed from src in
five places instead of one. They still turned the gate red, which is the worst
possible outcome: a gate passing for a reason nobody checked. Regenerating
from src means a mutant can only ever differ by its one intended change.

Run from tools/quorum-test/: python3 mut/make.py
"""
src = open('../../src/ov-quorum.js').read()
# 🔴 A MUTANT LIVES IN mut/, TWO LEVELS BELOW src/, so the element's own
# relative imports have to be rewritten or every mutant dies at import time -
# which the gate reports as a THROW, not as the refusal failing. A mutant that
# cannot load proves nothing about the refusal it was made to break.
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline, and the XL888T vote itself. Frozen channels rejoin the vote,
# so two stuck sensors can outvote the one that is still moving.
mut('a-frozen-votes',
    "      const mv = comp.filter((r) => !r.frozen);",
    "      const mv = comp.slice();  // MUTANT: a stuck channel votes")

# b: two left that disagree are averaged rather than refused.
mut('b-average-two',
    "        out = d <= tol",
    "        out = true  // MUTANT: average them whatever the distance")

# c: a rejection absorbed instead of announced.
mut('c-silent-reject',
    "        this.say(`${r.id} out-voted, miscompare ${c.mis} of ${failAfter}`);",
    "        void (`${r.id} out-voted, miscompare ${c.mis} of ${failAfter}`);  // MUTANT: say nothing")

# d: a channel removed from the set with nobody's name on it.
mut('d-anonymous-remove',
    "    if (!by || !String(by).trim()) {",
    "    if (false) {  // MUTANT: anyone may remove a channel")
