/* GENERATED by tools/gen_entry.py. Do not edit; re-run the script.
 *
 * Overscan, whole kit, one module:  import 'overscan'
 *
 * 🔴 EVERY IMPORT HERE IS A SIDE EFFECT AND NONE OF THEM IS DEAD CODE. Each
 * module registers its custom element on load, so a bundler told these files
 * are side-effect-free would tree-shake the entire kit and leave a page of
 * unupgraded tags with no error anywhere. package.json lists src/ov-*.js,
 * this file and the CSS under sideEffects for exactly this reason; only the
 * React/Vue wrappers and the shader modules sit outside it, so the ones nobody
 * imports can be dropped. Do not "optimise" the list.
 *
 * Importing a single element instead is supported and smaller:
 *     import 'overscan/src/ov-chart.js'
 * CSS is separate either way: import 'overscan/overscan.css'.
 */

import './ov-core.js';
import './ov-source.js';
import './ov-refusal.js';
import './ov-gl.js';
import './ov-allocator.js';
import './ov-annunciator.js';
import './ov-ansi.js';
import './ov-ascii.js';
import './ov-avatar.js';
import './ov-balance.js';
import './ov-baseline.js';
import './ov-chart.js';
import './ov-clearance.js';
import './ov-cli.js';
import './ov-consistency.js';
import './ov-continuity.js';
import './ov-countdown.js';
import './ov-coverage.js';
import './ov-dial.js';
import './ov-donut.js';
import './ov-dose.js';
import './ov-downlink.js';
import './ov-ecg.js';
import './ov-endurance.js';
import './ov-fan.js';
import './ov-fault.js';
import './ov-field.js';
import './ov-flap.js';
import './ov-flip.js';
import './ov-gauge.js';
import './ov-geo.js';
import './ov-geomap.js';
import './ov-graph.js';
import './ov-grid.js';
import './ov-histogram.js';
import './ov-hold.js';
import './ov-horizon.js';
import './ov-icons.js';
import './ov-keys.js';
import './ov-ladder.js';
import './ov-likelihood.js';
import './ov-locator.js';
import './ov-log.js';
import './ov-map.js';
import './ov-match.js';
import './ov-menu.js';
import './ov-modal.js';
import './ov-mosaic.js';
import './ov-orbit.js';
import './ov-ornament.js';
import './ov-plate.js';
import './ov-player.js';
import './ov-polygon.js';
import './ov-position.js';
import './ov-procedure.js';
import './ov-quorum.js';
import './ov-radar.js';
import './ov-rangebar.js';
import './ov-reticle.js';
import './ov-reveal.js';
import './ov-schematic.js';
import './ov-scope.js';
import './ov-score.js';
import './ov-segment.js';
import './ov-sequence.js';
import './ov-sound.js';
import './ov-sound-switch.js';
import './ov-split.js';
import './ov-station.js';
import './ov-switch.js';
import './ov-table.js';
import './ov-tabs.js';
import './ov-tactical.js';
import './ov-term.js';
import './ov-text.js';
import './ov-timeline.js';
import './ov-timestack.js';
import './ov-topology.js';
import './ov-track.js';
import './ov-transport.js';
import './ov-tree.js';
import './ov-verifier.js';
import './ov-vitals.js';
import './ov-waterfall.js';
import './ov-wave.js';
import './ov-window.js';
import './ov-wireframe.js';

export { Overscan, define } from './ov-core.js';
export { default as OverscanRefusal } from './ov-refusal.js';
