#!/usr/bin/env python3
"""Generate the ov-station mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

🔴 GENERATED, NOT HAND-WRITTEN. See tools/quorum-test/mut/make.py for why.

Run from tools/station-test/: python3 mut/make.py
"""
src = open('../../src/ov-station.js').read()
# 🔴 A MUTANT LIVES IN mut/, TWO LEVELS BELOW src/, so the element's own
# relative imports have to be rewritten or every mutant dies at import time -
# which the gate reports as a THROW, not as the refusal failing. A mutant that
# cannot load proves nothing about the refusal it was made to break.
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. Every kind of absence collapses into DETECTED NONE, which is
# the report reading "no thunderstorm" off a station that has no sensor for one.
mut('a-collapse-none',
    "        state = equipped === null ? 'unreadable' : name === 'cloud' ? (how === 'manual' ? 'clear' : 'ncd') : 'none';",
    "        state = 'none';  // MUTANT: absent means absent")

# b: the equipment list ignored, so NOT EQUIPPED never appears.
mut('b-equipped-ignored',
    "      if (equipped === false) state = 'not-equipped';",
    "      if (false) state = 'not-equipped';  // MUTANT: everything is equipped")

# c: no maintenance flag read as a clean bill of health.
mut('c-maint-ok',
    "      : m === false ? 'NO MAINTENANCE FLAG · not a health check: not all problems are self-detected'",
    "      : m === false ? 'OK'  // MUTANT: no flag means healthy")

# d: an absent age taken as zero, because Number(null) is 0.
mut('d-age-null-zero',
    "    const age = rawAge !== null && rawAge !== undefined && Number.isFinite(Number(rawAge))",
    "    const age = Number.isFinite(Number(rawAge))  // MUTANT: Number(null) is 0")
