#!/usr/bin/env python3
"""Generate the ov-clearance mutants: one copy of the element per refusal, each
with that refusal broken on purpose. The gate MUST go red against every one.

A green gate run only proves the harness ran. This element passed 33/33 on its
first run, which is exactly when a gate is least worth believing.

Run from tools/clearance-test/: python3 mut/make.py
"""
src = open('../../src/ov-clearance.js').read()

# A mutant sits two levels below src/, so the element's own relative imports
# have to be rewritten or it dies at import time - which the gate reports as a
# THROW, not as the refusal failing.
for _a, _b in (("from './ov-", "from '../../../src/ov-"), ("import './ov-", "import '../../../src/ov-")):
    src = src.replace(_a, _b)

head = ("/* MUTANT: one refusal broken on purpose. The gate MUST go red against this\n"
        " * file. Generated by mut/make.py; never edited by hand.\n */\n")


def mut(name, old, new):
    assert src.count(old) == 1, (name, src.count(old))
    open('mut/%s.js' % name, 'w').write(head + src.replace(old, new))
    print('wrote', name)


# a: the headline. The charted figure is reported as the clearance, which is
# the PAZIFIK's ECDIS exactly.
mut('a-charted-is-clearance',
    "    r.worst = r.charted - widen;",
    "    r.worst = r.charted;  // MUTANT: the chart is believed as drawn")

# b: no zone of confidence, so fall back to the charted distance rather than
# refusing - the "it is probably fine" failure.
mut('b-fallback-unqualified',
    "      r.state = 'unqualified';\n"
    "      r.why = 'NOT QUALIFIED · the chart does not say how good the survey is';\n"
    "      return done();",
    "      r.state = 'qualified';  // MUTANT: no zone, take the chart at its word\n"
    "      r.worst = r.charted;\n"
    "      return done();")

# c: unassessed taken at face value instead of as D.
mut('c-u-is-surveyed',
    "    r.asD = !!ZOC[worstZone].asD;",
    "    r.asD = false;  // MUTANT: U is a zone like any other")

# d: where two zones meet, the BETTER one wins.
mut('d-better-zone-wins',
    "    const worstZone = p.zones.slice().sort((a, b) => ORDER.indexOf(b) - ORDER.indexOf(a))[0];",
    "    const worstZone = p.zones.slice().sort((a, b) => ORDER.indexOf(a) - ORDER.indexOf(b))[0];"
    "  // MUTANT: the kinder zone")

# e: invent an accuracy for a zone whose figure this kit has never read.
mut('e-invent-zone-figure',
    "    r.accuracy = p.accuracy !== null ? p.accuracy : ZOC[worstZone].m;",
    "    r.accuracy = p.accuracy !== null ? p.accuracy : (ZOC[worstZone].m ?? 50);"
    "  // MUTANT: remember a number for B")

# f: judge the margin against the charted figure, so the alarm comes too late.
mut('f-margin-on-charted',
    "      r.breaches = r.worst < margin;",
    "      r.breaches = r.charted < margin;  // MUTANT: alarm on the chart, not the truth")

# g: a missing survey date passes silently.
mut('g-silent-survey-gap',
    "    setText(q('.ov-clearance__survey'), r.surveyed ? `SURVEYED ${r.surveyed}` : 'SURVEY DATE NOT GIVEN');\n"
    "    setAttr(q('.ov-clearance__survey'), 'data-ov-missing', r.surveyed ? null : '');",
    "    setText(q('.ov-clearance__survey'), r.surveyed ? `SURVEYED ${r.surveyed}` : '');\n"
    "    setAttr(q('.ov-clearance__survey'), 'data-ov-missing', null);  // MUTANT: say nothing")
